<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Modelado estadístico | Ciencia de Datos para Activismo Jurídico</title>
  <meta name="description" content="7 Modelado estadístico | Ciencia de Datos para Activismo Jurídico" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Modelado estadístico | Ciencia de Datos para Activismo Jurídico" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="bitsandbricks/CD_AJ" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Modelado estadístico | Ciencia de Datos para Activismo Jurídico" />
  
  
  

<meta name="author" content="Antonio Vazquez Brust" />
<meta name="author" content="Demian Zayat" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="trabajando-con-datos-espaciales-y-temporales.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ciencia de Datos para Activismo Jurídico</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>¿Para quién es esto?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#antes-de-empezar"><i class="fa fa-check"></i>Antes de empezar</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="qué-es-la-ciencia-de-datos.html"><a href="qué-es-la-ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> ¿Qué es la ciencia de datos?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="qué-es-la-ciencia-de-datos.html"><a href="qué-es-la-ciencia-de-datos.html#qué-significa-hacer-ciencia-de-datos"><i class="fa fa-check"></i><b>1.1</b> ¿Qué significa hacer ciencia de datos?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html"><i class="fa fa-check"></i><b>2</b> Una presentación a toda marcha de R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#nuestro-primer-proyecto-en-r"><i class="fa fa-check"></i><b>2.1</b> Nuestro primer proyecto en R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#a-investigar-cual-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><i class="fa fa-check"></i><b>2.1.1</b> A investigar: ¿Cual es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
<li class="chapter" data-level="2.1.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#crear-un-proyecto-en-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Crear un proyecto en RStudio</a></li>
<li class="chapter" data-level="2.1.3" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#escribiendo-un-script"><i class="fa fa-check"></i><b>2.1.3</b> Escribiendo un script</a></li>
<li class="chapter" data-level="2.1.4" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#cargar-los-datos"><i class="fa fa-check"></i><b>2.1.4</b> Cargar los datos</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#visualización-la-exploración-gráfica-de-la-información"><i class="fa fa-check"></i><b>2.2</b> Visualización: la exploración gráfica de la información</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#haciendo-mapas"><i class="fa fa-check"></i><b>2.2.1</b> Haciendo mapas</a></li>
<li class="chapter" data-level="2.2.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#agregando-datos"><i class="fa fa-check"></i><b>2.2.2</b> Agregando datos</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#el-veredicto-final"><i class="fa fa-check"></i><b>2.3</b> El veredicto final</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#cuál-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><i class="fa fa-check"></i><b>2.3.1</b> ¿Cuál es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#ejercicios"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html"><i class="fa fa-check"></i><b>3</b> Poniendo los datos en forma</a>
<ul>
<li class="chapter" data-level="3.1" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#primeros-pasos-al-examinar-un-conjunto-de-datos-nuevo"><i class="fa fa-check"></i><b>3.1</b> Primeros pasos al examinar un conjunto de datos nuevo</a></li>
<li class="chapter" data-level="3.2" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#cruzando-variables-la-operación-join"><i class="fa fa-check"></i><b>3.2</b> Cruzando variables: la operación <code>join</code></a></li>
<li class="chapter" data-level="3.3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#transformando-los-datos"><i class="fa fa-check"></i><b>3.3</b> Transformando los datos</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#seleccionar-columnas-con-select"><i class="fa fa-check"></i><b>3.3.1</b> Seleccionar columnas con <code>select()</code></a></li>
<li class="chapter" data-level="3.3.2" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#filtrar-filas-con-filter"><i class="fa fa-check"></i><b>3.3.2</b> Filtrar filas con <code>filter()</code></a></li>
<li class="chapter" data-level="3.3.3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#ordenar-filas-con-arrange"><i class="fa fa-check"></i><b>3.3.3</b> Ordenar filas con <code>arrange()</code></a></li>
<li class="chapter" data-level="3.3.4" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#agregar-nuevas-variables-con-mutate"><i class="fa fa-check"></i><b>3.3.4</b> Agregar nuevas variables con <code>mutate()</code></a></li>
<li class="chapter" data-level="3.3.5" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#extraer-resúmenes-con-summarise"><i class="fa fa-check"></i><b>3.3.5</b> Extraer resúmenes con <code>summarise()</code></a></li>
<li class="chapter" data-level="3.3.6" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#bonus-el-operador-pipe"><i class="fa fa-check"></i><b>3.3.6</b> ¡BONUS! El operador “pipe”: <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#ejercicios-1"><i class="fa fa-check"></i><b>3.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualización.html"><a href="visualización.html"><i class="fa fa-check"></i><b>4</b> Visualización</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visualización.html"><a href="visualización.html#una-buena-visualización-para-empezar-el-scatterplot"><i class="fa fa-check"></i><b>4.1</b> Una buena visualización para empezar: el <em>scatterplot</em></a></li>
<li class="chapter" data-level="4.2" data-path="visualización.html"><a href="visualización.html#ajustando-color-y-tamaño"><i class="fa fa-check"></i><b>4.2</b> Ajustando color y tamaño</a></li>
<li class="chapter" data-level="4.3" data-path="visualización.html"><a href="visualización.html#facetado"><i class="fa fa-check"></i><b>4.3</b> Facetado</a></li>
<li class="chapter" data-level="4.4" data-path="visualización.html"><a href="visualización.html#gráficos-de-barras"><i class="fa fa-check"></i><b>4.4</b> Gráficos de barras</a></li>
<li class="chapter" data-level="4.5" data-path="visualización.html"><a href="visualización.html#histogramas"><i class="fa fa-check"></i><b>4.5</b> Histogramas</a></li>
<li class="chapter" data-level="4.6" data-path="visualización.html"><a href="visualización.html#preparando-una-visualización-para-compartir"><i class="fa fa-check"></i><b>4.6</b> Preparando una visualización para compartir</a></li>
<li class="chapter" data-level="4.7" data-path="visualización.html"><a href="visualización.html#otras-visualizaciones"><i class="fa fa-check"></i><b>4.7</b> Otras visualizaciones</a></li>
<li class="chapter" data-level="4.8" data-path="visualización.html"><a href="visualización.html#ejercicios-2"><i class="fa fa-check"></i><b>4.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html"><i class="fa fa-check"></i><b>5</b> Analisis de texto</a>
<ul>
<li class="chapter" data-level="5.1" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#manipulación-de-texto"><i class="fa fa-check"></i><b>5.1</b> Manipulación de texto</a></li>
<li class="chapter" data-level="5.2" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#metacaracteres"><i class="fa fa-check"></i><b>5.2</b> Metacaracteres</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#comienzo-y-fin-de-línea"><i class="fa fa-check"></i><b>5.2.1</b> Comienzo y fin de línea</a></li>
<li class="chapter" data-level="5.2.2" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#clases-de-palabras"><i class="fa fa-check"></i><b>5.2.2</b> Clases de Palabras</a></li>
<li class="chapter" data-level="5.2.3" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#lookaround"><i class="fa fa-check"></i><b>5.2.3</b> Lookaround</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#primer-ejercicio"><i class="fa fa-check"></i><b>5.3</b> Primer ejercicio</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#consiguiendo-los-datos"><i class="fa fa-check"></i><b>5.3.1</b> Consiguiendo los datos</a></li>
<li class="chapter" data-level="5.3.2" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#limpieza-de-datos"><i class="fa fa-check"></i><b>5.3.2</b> Limpieza de datos</a></li>
<li class="chapter" data-level="5.3.3" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#análisis"><i class="fa fa-check"></i><b>5.3.3</b> Análisis</a></li>
<li class="chapter" data-level="5.3.4" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#quienes-hablaron"><i class="fa fa-check"></i><b>5.3.4</b> Quienes hablaron?</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#ejercicios-3"><i class="fa fa-check"></i><b>5.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html"><i class="fa fa-check"></i><b>6</b> Trabajando con datos espaciales y temporales</a>
<ul>
<li class="chapter" data-level="6.1" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#trabajando-con-fechas"><i class="fa fa-check"></i><b>6.1</b> Trabajando con fechas</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#la-fecha-como-clase-de-variable"><i class="fa fa-check"></i><b>6.1.1</b> La fecha como clase de variable</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#mirando-al-espacio"><i class="fa fa-check"></i><b>6.2</b> Mirando al espacio</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#obteniendo-un-mapa-base"><i class="fa fa-check"></i><b>6.2.1</b> Obteniendo un mapa base</a></li>
<li class="chapter" data-level="6.2.2" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#de-coordenadas-al-mapa"><i class="fa fa-check"></i><b>6.2.2</b> De coordenadas al mapa</a></li>
<li class="chapter" data-level="6.2.3" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#mapas-de-densidad"><i class="fa fa-check"></i><b>6.2.3</b> Mapas de densidad</a></li>
<li class="chapter" data-level="6.2.4" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#visualizando-multiples-categorías"><i class="fa fa-check"></i><b>6.2.4</b> Visualizando multiples categorías</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#combinando-espacio-y-tiempo"><i class="fa fa-check"></i><b>6.3</b> Combinando espacio y tiempo</a></li>
<li class="chapter" data-level="6.4" data-path="trabajando-con-datos-espaciales-y-temporales.html"><a href="trabajando-con-datos-espaciales-y-temporales.html#ejercicios-4"><i class="fa fa-check"></i><b>6.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html"><i class="fa fa-check"></i><b>7</b> Modelado estadístico</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#regresión-lineal-simple"><i class="fa fa-check"></i><b>7.1</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#regresión-con-una-variable-numérica"><i class="fa fa-check"></i><b>7.1.1</b> Regresión con una variable numérica</a></li>
<li class="chapter" data-level="7.1.2" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#revolviendo-los-residuos"><i class="fa fa-check"></i><b>7.1.2</b> Revolviendo los residuos</a></li>
<li class="chapter" data-level="7.1.3" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#cómo-estamos-de-confianza"><i class="fa fa-check"></i><b>7.1.3</b> ¿Cómo estamos de confianza?</a></li>
<li class="chapter" data-level="7.1.4" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#regresión-con-una-variable-categórica"><i class="fa fa-check"></i><b>7.1.4</b> Regresión con una variable categórica</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#regresión-con-múltiples-variables"><i class="fa fa-check"></i><b>7.2</b> Regresión con múltiples variables</a></li>
<li class="chapter" data-level="7.3" data-path="modelado-estadístico.html"><a href="modelado-estadístico.html#ejercicios-5"><i class="fa fa-check"></i><b>7.3</b> Ejercicios</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ciencia de Datos para Activismo Jurídico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelado-estadístico" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Modelado estadístico<a href="modelado-estadístico.html#modelado-estadístico" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="imagenes/modelado.jpg" width="100%" /></p>
<p>Llegamos a un tema de gran interés para quienes realizan investigaciones formales. La posición central que tiene el modelado en la investigación científica se debe a que cuantifica relaciones: permite pasar de decir “Los afroamericanos suelen pagar más en la adquisición de autos” a “Los vendedores hacen ofertas finales a los afroamericanos $287 dólares más caras que a los blancos”<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. La cuantificación permite realizar comparaciones, algo clave para entender un fenómeno estudiado: antes y después, con o sin tratamiento, en un lugar o en otro.</p>
<p>En términos matemáticos, se habla de “modelar” debido a que estamos creando un modelo, una reconstrucción simplificada (¡simplificada en extremo!) de cómo funciona un proceso observado en el mundo real. En un modelo de datos, siempre tenemos al menos</p>
<ul>
<li>Una variable resultante, también llamada variable “dependiente”,</li>
<li>Una o más variables predictoras, también llamadas “explicativas”</li>
</ul>
<p>El modelado de datos puede ser utilizado para dos propósitos:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Predecir</strong> el valor de una variable resultante en base a valores conocidos de las variables predictoras. Aquí no interesa tanto entender cómo es que las variables interactúan entre sí, o por qué lo hacen. Mientras las predicciones sean acertadas, o se acerquen lo suficiente, el modelo cumple su cometido. Los modelos predictivos se emplean en una enorme variedad de aplicaciones: inversión en bolsa, prevención de fraude, publicidad online, fijación de primas en seguros de riesgo, etc.</p></li>
<li><p><strong>Explicar</strong> la relación entre una variable dependiente y todas las demás (las explicativas), buscando determinar si la relación es significativa. Los modelos explicativos son los que se favorecen en investigación académica, ya que ayudan a entender el fenómeno modelado.</p></li>
</ol>
<p>Existen muchísimas técnicas para modelar datos, algunas de ellas simples como la regresión lineal, y otras mucho más complejas, como las redes neuronales. Vamos a practicar con las primeras.</p>
<p>La humilde regresión lineal, fácil de explicar y muy fácil de resolver con la ayuda de una computadora, es el caballito de batalla del modelado estadístico. A pesar de que no es adecuada para ciertos tipo de datos, y de que existen métodos más modernos que explotan mucho más el potencial de las computadoras, la regresión lineal sigue siendo una herramienta de uso muy extendido. Un poco por costumbre, y otro porque es el método más fácil de interpretar, lo que favorece entender y comunicar sus resultados.</p>
<p>Este capítulo le debe mucho a <em>ModernDive: An Introduction to Statistical and Data Sciences via R</em> por Chester Ismay y Albert Y. Kim, disponible en forma gratuita en <a href="http://moderndive.com/" class="uri">http://moderndive.com/</a>. ModernDive es un recurso muy recomendable para quienes quieran profundizar su conocimiento más allá de los temas que veremos a continuación. Vamos a usar el paquete de R homónimo, <code>moderndive</code>, que acompaña al libro y provee funciones que facilitan el aprendizaje de modelos estadísticos.</p>
<p>Antes de continuar, lo instalamos (¡sólo hace falta realizar esto una vez!)</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="modelado-estadístico.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;moderndive&quot;</span>)</span></code></pre></div>
<p>Y lo activamos:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="modelado-estadístico.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span></code></pre></div>
<div id="regresión-lineal-simple" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Regresión lineal simple<a href="modelado-estadístico.html#regresión-lineal-simple" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La encarnación más sencilla de la regresión lineal es la simple o univariada. Tenemos nuestra variable <span class="math inline">\(y\)</span>, numérica, y una sola variable predictora <span class="math inline">\(x\)</span>, que puede ser numérica o categórica.</p>
<p>Para poner en práctica los conceptos repasados en este capítulo, vamos a recurrir a un dataset compilado por <a href="https://fivethirtyeight.com/"><em>FiveThirtyEight</em></a>, un sitio web dedicado al análisis estadístico y periodístico de datos de política, economía y deportes. Sus artículos suelen ser acompañados de los datos originales utilizados para el análisis, lo que permite a la audiencia verificar los hallazgos y realizar sus propias pesquisas.</p>
<p>El dataset con el que trabajaremos registra la tasa promedio de <a href="https://victimconnect.org/tipos-de-delitos/crimenes-de-odio/">crímenes de odio</a> reportados en Estados Unidos durante el período 2010-2015, a nivel estado, junto con indicadores demográficos de cada lugar. Los <a href="https://github.com/fivethirtyeight/data/tree/master/hate-crimes">datos</a> fueron presentados por <em>FiveThirtyEight</em> en un <a href="https://fivethirtyeight.com/features/higher-rates-of-hate-crimes-are-tied-to-income-inequality/">artículo</a> que explora la relación entre desigualdad socioeconómica y crímenes de odio.</p>
<p>Descarguemos entonces el dataset (que hemos traducido pra facilitar su uso), y echemosle un vistazo como ya sabemos hacer:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="modelado-estadístico.html#cb3-1" aria-hidden="true" tabindex="-1"></a>crimenes_odio <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://cdaj.netlify.app/data/crimenes_odio_EEUU.csv&quot;</span>)</span>
<span id="cb3-2"><a href="modelado-estadístico.html#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="modelado-estadístico.html#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crimenes_odio)</span></code></pre></div>
<pre><code>##     estado          mediana_ingreso_hogares pct_desocupados
##  Length:50          Min.   :35.52           Min.   :2.800  
##  Class :character   1st Qu.:48.36           1st Qu.:4.200  
##  Mode  :character   Median :54.61           Median :5.050  
##                     Mean   :54.96           Mean   :4.922  
##                     3rd Qu.:60.65           3rd Qu.:5.700  
##                     Max.   :76.17           Max.   :7.300  
##                                                            
##  pct_reside_area_metro pct_secundaria_completa pct_no_ciudadanos
##  Min.   : 31.00        Min.   :79.90           Min.   : 1.00    
##  1st Qu.: 63.00        1st Qu.:83.97           1st Qu.: 3.00    
##  Median : 78.50        Median :87.50           Median : 4.00    
##  Mean   : 74.52        Mean   :86.91           Mean   : 5.34    
##  3rd Qu.: 88.50        3rd Qu.:89.80           3rd Qu.: 8.00    
##  Max.   :100.00        Max.   :91.80           Max.   :13.00    
##                                                NA&#39;s   :3        
##  pct_pobreza_blancos  indice_gini     pct_no_blancos  pct_votantes_trump
##  Min.   : 5.00       Min.   :0.4190   Min.   : 6.00   Min.   :30.00     
##  1st Qu.: 8.00       1st Qu.:0.4400   1st Qu.:19.25   1st Qu.:42.00     
##  Median : 9.00       Median :0.4530   Median :27.50   Median :49.50     
##  Mean   : 9.28       Mean   :0.4522   Mean   :30.94   Mean   :49.90     
##  3rd Qu.:10.00       3rd Qu.:0.4657   3rd Qu.:42.00   3rd Qu.:57.75     
##  Max.   :17.00       Max.   :0.4990   Max.   :81.00   Max.   :70.00     
##                                                                         
##  crimenes_odio_100k_splc crimenes_odio_prom_100k_fbi trump_electo   
##  Min.   :0.06745         Min.   :0.2669              Mode :logical  
##  1st Qu.:0.14219         1st Qu.:1.2826              FALSE:19       
##  Median :0.22576         Median :1.9371              TRUE :31       
##  Mean   :0.27761         Mean   :2.1924                             
##  3rd Qu.:0.34681         3rd Qu.:3.1361                             
##  Max.   :0.83285         Max.   :4.8019                             
##  NA&#39;s   :4               NA&#39;s   :1</code></pre>
<p>Aclaremos el significado de cada columna:</p>
<table>
<colgroup>
<col width="25%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Definición</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>estado</code></td>
<td>Nombre del estado</td>
</tr>
<tr class="even">
<td><code>mediana_ingreso_hogares</code></td>
<td>Mediana del ingreso de hogares (en miles USD), 2016</td>
</tr>
<tr class="odd">
<td><code>pct_desocupados</code></td>
<td>Porcentaje de población desocupada, Sept. 2016</td>
</tr>
<tr class="even">
<td><code>pct_reside_area_metro</code></td>
<td>Porcentaje de población que reside en áreas metropolitanas, 2015</td>
</tr>
<tr class="odd">
<td><code>pct_secundaria_completa</code></td>
<td>Porcentaje de adultos (25+) con educación secundaria completa, 2009</td>
</tr>
<tr class="even">
<td><code>pct_no_ciudadanos</code></td>
<td>Porcentaje de población sin ciudadanía, 2015</td>
</tr>
<tr class="odd">
<td><code>pct_pobreza_blancos</code></td>
<td>Porcentaje de residentes blancos que viven en pobreza, 2015</td>
</tr>
<tr class="even">
<td><code>indice_gini</code></td>
<td>Indice Gini, 2015</td>
</tr>
<tr class="odd">
<td><code>pct_no_blancos</code></td>
<td>Porcentaje de población no blanca, 2015</td>
</tr>
<tr class="even">
<td><code>pct_votantes_trump</code></td>
<td>Porcentaje de votantes en las elecciones presidenciales 2016 que votaron por Donald Trump</td>
</tr>
<tr class="odd">
<td><code>crimenes_odio_100k_splc</code></td>
<td>Crímenes de odio cada 100.000 habitantes, Southern Poverty Law Center, 2016</td>
</tr>
<tr class="even">
<td><code>crimenes_odio_prom_100k_fbi</code></td>
<td>Promedio anual de crímenes de odio cada 100.000 habitante, FBI, 2010-2015</td>
</tr>
</tbody>
</table>
<p>Con el poder de <code>summary()</code>, comprobar que la incidencia de crímenes de odio varía de forma considerable entre estados. El promedio anual 2010-2015 reportado por el FBI (variable “crimenes_odio_prom_100k_fbi”) va de 0,2 a casi 5 incidentes cada 100.000 habitantes. Algo similar ocurre con la cantidad reportada con otra metodología, los datos para 2016 del <em>Southern Poverty Law Center</em> (“crimenes_odio_100k_splc”): el rango va de apenas 0,067 incidentes cada 100.000 habitantes hasta 0,83 (¡12 veces más!).</p>
<div id="regresión-con-una-variable-numérica" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Regresión con una variable numérica<a href="modelado-estadístico.html#regresión-con-una-variable-numérica" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hagamos nuestra pregunta pregunta a contestar con una regresión lineal: ¿Cómo ha se relaciona el nivel de ingresos con la incidencia de crímenes de odio?</p>
<p>Como dijimos en el capítulo de visualización, los <em>scatterplots</em> son útiles para mostrar la relación entre dos variables. Usemos uno para visualizar la relación entre estas dos variables, para intentar anticipar los resultados de la regresión lineal.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="modelado-estadístico.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Si no lo hicimos antes, activamos el paquete tidyverse</span></span>
<span id="cb5-2"><a href="modelado-estadístico.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.3.3     ✔ purrr   0.3.4
## ✔ tibble  3.1.7     ✔ dplyr   1.0.9
## ✔ tidyr   1.2.0     ✔ stringr 1.4.0
## ✔ readr   1.4.0     ✔ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="modelado-estadístico.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> crimenes_odio) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="modelado-estadístico.html#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> mediana_ingreso_hogares, <span class="at">y =</span> crimenes_odio_prom_100k_fbi)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="modelado-estadístico.html#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Correlación entre ingesos medios por hogar y crímenes de odio&quot;</span>,</span>
<span id="cb9-4"><a href="modelado-estadístico.html#cb9-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">&quot;Crímenes cada 100.000 habitantes, promedio 2010-2016&quot;</span>,</span>
<span id="cb9-5"><a href="modelado-estadístico.html#cb9-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">&quot;mediana de ingresos por hogar (miles USD)&quot;</span>,</span>
<span id="cb9-6"><a href="modelado-estadístico.html#cb9-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&quot;tasa de crímenes&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Los opiniones pueden variar pero aquí parece mostrarse una correlación más bien débil entre las variables, en forma positiva. Esto es, el incremento de la mediana de ingresos por hogar resulta en un incremento en la tasa de crímenes de odio, pero en este caso no de forma drástica. Una correlación <em>negativa</em> sería lo opuesto: que el incremento de la variable explicativa estuviera asociado a un decremento de la variable explicada. Además del <em>signo</em> de una correlación, otra medida importante es su intensidad. La intensidad de una correlación va de -1 (correlación negativa total) a 1 (correlación positiva total). Una correlación de cero significa que las dos variables son por completo independientes. En en ese caso, saber cuánto vale una no nos ayuda a estimar el valor de la otra.</p>
<p>Para obtener la correlación entre dos variables podemos usar <code>get_correlation</code>, una función provista por el paquete <code>moderndive</code>. Ponemos el nombre de la variable a explicar en el lado izquierdo del signo “~” (o “tilde”), y ponemos el nombre de la variable explicativa en el lado derecho. Esta forma de escribir la relación entre variables es común en las funciones estadísticas de <em>R</em>, y se le llama “notación de fórmula”. No hay que preocuparse mucho por ella, ya nos acostumbraremos a usarla.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="modelado-estadístico.html#cb11-1" aria-hidden="true" tabindex="-1"></a>crimenes_odio <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="modelado-estadístico.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_correlation</span>(crimenes_odio_prom_100k_fbi <span class="sc">~</span> mediana_ingreso_hogares, </span>
<span id="cb11-3"><a href="modelado-estadístico.html#cb11-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["cor"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.242131"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="warning">
<p>Usamos el parámetro <code>na.rm = TRUE</code> para descartar las filas donde no contamos con un valor para cualquiera de las dos variables de interés. Nuestro dataset efectivamente tiene algunos valores faltantes (véase otra vez la salida de <code>summary(crimenes_odio)</code> para comprobarlo), así que con eso evitamos que la función falle al intentar calcular la correlación.</p>
</div>
<p>¿A partir de qué valor consideramos que existe una correlación considerable? La verdad es que no hay una regla a seguir, pero inventemos una. Si el valor absoluto de la correlación es…</p>
<pre><code>- de 0,7 a 1: de fuerte a total
- de 0,5 a 0,7: de moderada a fuerte
- de 0,3 a 0,5: de débil a moderada
- menor a 0,3: de nula a débil</code></pre>
<p>El valor que obtuvimos no llega al 0,3; podemos decir que la correlación es débil. Pero aún desconocemos algo quizás más importante: un valor preciso del “efecto” que la variable de ingresos tiene sobre la tasa de crímenes. Eso es lo que vamos a determinar con la regresión lineal. Usamos la palabra “efecto” entre comillas para aclarar una de las limitaciones del modelado estadístico: podemos probar correlación, pero no causalidad. Es decir, no podemos probar que una variable causa a la otra; en todo caso, probamos que se mueven juntas y en base a ello podríamos diseñar un experimento que permita comprobar causalidad.</p>
<p><img src="https://imgs.xkcd.com/comics/correlation.png" /></p>
<p>Vamos a la regresión lineal entonces, para establecer de una buena vez la correlación entre ingresos y crímenes de odio. Usamos la función <code>lm()</code> (por “linear model”), así:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="modelado-estadístico.html#cb13-1" aria-hidden="true" tabindex="-1"></a>modelo_ingresos <span class="ot">&lt;-</span> <span class="fu">lm</span>(crimenes_odio_prom_100k_fbi <span class="sc">~</span> mediana_ingreso_hogares, </span>
<span id="cb13-2"><a href="modelado-estadístico.html#cb13-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> crimenes_odio)</span>
<span id="cb13-3"><a href="modelado-estadístico.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="modelado-estadístico.html#cb13-4" aria-hidden="true" tabindex="-1"></a>modelo_ingresos</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = crimenes_odio_prom_100k_fbi ~ mediana_ingreso_hogares, 
##     data = crimenes_odio)
## 
## Coefficients:
##             (Intercept)  mediana_ingreso_hogares  
##                 0.41199                  0.03259</code></pre>
<p>¡Eso es todo! Hemos construido un modelo estadístico; ahora tenemos que aprender a usarlo. Obsérvese que volvió aparecer el simbolillo que denota una fórmula, <code>~</code>. Usado como primer argumento de <code>lm()</code>, significa “<em>crimenes_odio_prom_100k_fbi</em> vs <em>mediana_ingreso_hogares</em>”, es decir “estimar el efecto en la variable <em>crimenes_odio_prom_100k_fbi</em> cuando incrementa el valor de <em>mediana_ingreso_hogares</em>”, usando los datos contenidos en el dataframe <em>crimenes_odio</em>.</p>
<p>El resultado de <code>lm()</code>, que hemos guardado dentro de la variable <code>modelo_ingresos</code> es un tipo de objecto con el que no hemos trabajado hasta ahora. No es un dataframe, sino una lista que contiene distintos atributos del modelo estadístico. No hace falta detenernos en eso ahora.</p>
<p>Retomando nuestra pregunta… ¿cuál es el efecto? Lo obtenemos dándole el modelo que generamos a la función <code>get_regression_table()</code>, que devuelve una prolija tabla:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="modelado-estadístico.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(modelo_ingresos)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["lower_ci"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["upper_ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"intercept","2":"0.412","3":"1.054","4":"0.391","5":"0.698","6":"-1.708","7":"2.532"},{"1":"mediana_ingreso_hogares","2":"0.033","3":"0.019","4":"1.711","5":"0.094","6":"-0.006","7":"0.071"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Ahí está. En nuestro modelo, el efecto <em>estimado</em> de la variable <em>mediana_ingreso_hogares</em> es de 0.033. Significado: incrementando en una unidad la variable predictora, la variable a predecir se incrementa en 0.033. Dicho de otra manera, y expresándolo en las unidades de nuestras variables: por cada mil dólares de incremento en la mediana de ingresos por hogar, la tasa de crímenes de odio cada 100.000 habitantes se incrementa en 0.033 casos.</p>
<p>El otro término que aparece, “intercept” es la <em>intersección</em>. Para interpretar el modelo, la intersección rara vez tiene utilidad. Para lo que sí sirve es para trazar la línea que permite “predecir” valores para años en los que no tenemos observaciones. Recordemos la fórmula que define una línea recta:</p>
<p><span class="math display">\[ y = a + b \times x \]</span></p>
<p>A cada punto en <span class="math inline">\(x\)</span> le corresponde un valor en <span class="math inline">\(y\)</span> que se obtiene multiplicando a <span class="math inline">\(x\)</span> por la <em>pendiente</em>, <span class="math inline">\(b\)</span>, y sumando la intersección, <span class="math inline">\(a\)</span>. Se le llama “intersección” u “ordenada al origen” porque es el valor donde la recta intersecta con el eje de las <code>y</code>: cuando <span class="math inline">\(x\)</span> vale <span class="math inline">\(0\)</span>, la fórmula nos da <span class="math inline">\(y = b\)</span>.</p>
<p>En una regresión lineal, el “modelo” que creamos es precisamente eso: una línea. Tan simple como eso. Lo que la hace tan potente es que la podemos usar como bola de cristal: para saber cuanto valdría la variable dependiente ante un valor determinado de la variable predictora, revisamos por donde pasa la línea.</p>
<p>Lo podemos visualizar con ayuda de <code>ggplot()</code>, que por supuesto incluye una función para trazar líneas. Parámetros necesarios: <em>intercept</em> (intersección) y <em>slope</em> (pendiente). Usamos los respectivos valores que nos indica el modelo, <code>0.412</code> y <code>0.033</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="modelado-estadístico.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> crimenes_odio) <span class="sc">+</span> </span>
<span id="cb16-2"><a href="modelado-estadístico.html#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> mediana_ingreso_hogares, <span class="at">y =</span> crimenes_odio_prom_100k_fbi)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="modelado-estadístico.html#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Correlación entre ingesos medios por hogar y crímenes de odio&quot;</span>,</span>
<span id="cb16-4"><a href="modelado-estadístico.html#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">&quot;Crímenes cada 100.000 habitanes, promedio 2010-2016&quot;</span>,</span>
<span id="cb16-5"><a href="modelado-estadístico.html#cb16-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">&quot;mediana de ingresos por hogar (miles USD)&quot;</span>,</span>
<span id="cb16-6"><a href="modelado-estadístico.html#cb16-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&quot;tasa de crímenes&quot;</span>,</span>
<span id="cb16-7"><a href="modelado-estadístico.html#cb16-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">caption =</span> <span class="st">&quot;con línea de regresión&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="modelado-estadístico.html#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fl">0.412</span>, <span class="at">slope =</span> <span class="fl">0.033</span>), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Es hora de dar una definición oficial para una regresión lineal, y es esta: es la línea que describe la ecuación:</p>
<p><span class="math display">\[ \hat{y} = b_0 + b_1 \times x \]</span> Obsérvese que se trata de la ecuación de una recta, <span class="math inline">\(y = a + b \times x\)</span>, con otros nombres. En voz alta, se leería así “Cada predicción del valor de y, llamada <span class="math inline">\(\hat{y}\)</span>, se obtiene multiplicando a la variable predictora <span class="math inline">\(x\)</span> por su coeficiente <span class="math inline">\(b_1\)</span> y sumándole el valor de la intersección <span class="math inline">\(b_0\)</span>”. En otras palabras, a cada valor de <span class="math inline">\(x\)</span> (las observaciones de la variable explicativa) le corresponde un punto en la recta trazada por el modelo. La altura sobre la recta de las <span class="math inline">\(y\)</span> para ese punto es el valor predicho para la variable dependiente. Por ejemplo, si quisiéramos estimar la</p>
<p>Ya que estamos, aprendamos otro truco. <code>ggplot()</code> puede agregar a nuestros scatterplots una capa con la línea de la regresión lineal, en forma automática. La función <code>geom_smooth()</code> se usar para explicitar patrones en los datos. Tal como otras de la familia ggplot, espera que se le diga que variables asignar a <code>x</code> e <code>y</code>, más un parámetro <code>method</code> con el método solicitado para trazar una línea de tendencia. Aquí usamos <code>method = "lm"</code> por <em>linear model</em>, el modelo lineal.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="modelado-estadístico.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> crimenes_odio) <span class="sc">+</span> </span>
<span id="cb18-2"><a href="modelado-estadístico.html#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> mediana_ingreso_hogares, <span class="at">y =</span> crimenes_odio_prom_100k_fbi)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="modelado-estadístico.html#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Correlación entre ingesos medios por hogar y crímenes de odio&quot;</span>,</span>
<span id="cb18-4"><a href="modelado-estadístico.html#cb18-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">&quot;Crímenes cada 100.000 habitantes, promedio 2010-2016&quot;</span>,</span>
<span id="cb18-5"><a href="modelado-estadístico.html#cb18-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">&quot;mediana de ingresos por hogar (miles USD)&quot;</span>,</span>
<span id="cb18-6"><a href="modelado-estadístico.html#cb18-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&quot;tasa de crímenes&quot;</span>,</span>
<span id="cb18-7"><a href="modelado-estadístico.html#cb18-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">caption =</span> <span class="st">&quot;con línea de regresión vía geom_smooth()&quot;</span>) <span class="sc">+</span></span>
<span id="cb18-8"><a href="modelado-estadístico.html#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x =</span> mediana_ingreso_hogares, <span class="at">y =</span> crimenes_odio_prom_100k_fbi), </span>
<span id="cb18-9"><a href="modelado-estadístico.html#cb18-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Hacer una regresión lineal se trata de encontrar la línea que atraviesa nuestra nube de puntos de modo tal que la suma de las distancias de cada punto a la línea sea la menor posible. Es un problema matemático que puede resolverse con distintas técnicas (álgebra lineal, geometría, etc) que no vamos a discutir aquí. Confiaremos en R para hacer los cálculos.</p>
<p>En la relación ingresos - crímenes las distancias entre los puntos (las observaciones) y la línea (el modelo) varían bastante entre casos. Eso indica que el modelo no describe con gran precisión la dinámica de la relación entre las variables analizadas.</p>
<p>En general, es inusual encontrar una correlación nítida entre variables “en la vida real”, sobre todo cuando estudiamos procesos complejos cuyo comportamiento describe patrones más complejos que una relación lineal pura.</p>
<p>¿Debería preocuparnos eso? No siempre. A veces la regresión sirve más para cuantificar la relación entre dos variables, en sentido general, y no para realizar certeras predicciones o caracterizar de forma exacta un fenómeno con solo disponer de una variable explicativa. Si nos conformamos con eso, lo importante es que nuestro modelo sea “justo”, proveyendo un estimado con errores mas o menos parejos. Es decir, sin observaciones puntuales para las que el modelo resulta mucho peor que para otras.</p>
<p>Una parte importante del análisis basado en regresiones es revisar estos errores -la distancia entre el valor predicho y la observación-, y decidir si ameritan buscar una explicación. Para ello, lo mejor es empezar por prestar atención a los residuos.</p>
</div>
<div id="revolviendo-los-residuos" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Revolviendo los residuos<a href="modelado-estadístico.html#revolviendo-los-residuos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los residuos, en la jerga estadística, no son otra cosa que las diferencias encontradas entre el valor que predice un modelo para una variable y el valor observado en la práctica. Es decir, el valor para cada punto de <span class="math inline">\(y - \widehat{y}\)</span>. Los residuos representan el desvío de cada observación respecto al valor “esperado” por el modelo.</p>
<p>Cuando los desvíos son pequeños, es decir cuando los residuos son pequeños, decimos que nuestro modelo se ajusta bien a los datos observados. Cuando los residuos son grandes ocurre lo contrario, y quizás deberíamos buscar otra forma de describir -de modelar-, la relación entre las variables.</p>
<p>Prestemos atención a los residuos de nuestro modelo. Podemos extraer los residuos (y algunas cosillas más!) usando la función <code>get_regression_points()</code>,</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="modelado-estadístico.html#cb22-1" aria-hidden="true" tabindex="-1"></a>residuos_regresion <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(modelo_ingresos)</span>
<span id="cb22-2"><a href="modelado-estadístico.html#cb22-2" aria-hidden="true" tabindex="-1"></a>residuos_regresion</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["ID"],"name":[1],"type":["int"],"align":["right"]},{"label":["crimenes_odio_prom_100k_fbi"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["mediana_ingreso_hogares"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["crimenes_odio_prom_100k_fbi_hat"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["residual"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"1.806","3":"42.278","4":"1.790","5":"0.017"},{"1":"2","2":"1.657","3":"67.629","4":"2.616","5":"-0.959"},{"1":"3","2":"3.414","3":"49.254","4":"2.017","5":"1.397"},{"1":"4","2":"0.869","3":"44.922","4":"1.876","5":"-1.007"},{"1":"5","2":"2.398","3":"60.487","4":"2.383","5":"0.015"},{"1":"6","2":"2.805","3":"60.940","4":"2.398","5":"0.407"},{"1":"7","2":"3.773","3":"70.161","4":"2.699","5":"1.074"},{"1":"8","2":"1.470","3":"57.522","4":"2.287","5":"-0.817"},{"1":"9","2":"0.698","3":"46.140","4":"1.916","5":"-1.218"},{"1":"10","2":"0.412","3":"49.555","4":"2.027","5":"-1.615"},{"1":"11","2":"1.891","3":"53.438","4":"2.154","5":"-0.262"},{"1":"12","2":"1.044","3":"54.916","4":"2.202","5":"-1.158"},{"1":"13","2":"1.757","3":"48.060","4":"1.978","5":"-0.221"},{"1":"14","2":"0.561","3":"57.810","4":"2.296","5":"-1.735"},{"1":"15","2":"2.144","3":"53.444","4":"2.154","5":"-0.010"},{"1":"16","2":"4.208","3":"42.786","4":"1.806","5":"2.402"},{"1":"17","2":"1.341","3":"42.406","4":"1.794","5":"-0.453"},{"1":"18","2":"2.627","3":"51.710","4":"2.097","5":"0.529"},{"1":"19","2":"1.325","3":"76.165","4":"2.894","5":"-1.569"},{"1":"20","2":"4.802","3":"63.151","4":"2.470","5":"2.332"},{"1":"21","2":"3.200","3":"52.005","4":"2.107","5":"1.094"},{"1":"22","2":"3.612","3":"67.244","4":"2.603","5":"1.009"},{"1":"23","2":"0.623","3":"35.521","4":"1.570","5":"-0.947"},{"1":"24","2":"1.909","3":"56.630","4":"2.258","5":"-0.349"},{"1":"25","2":"2.955","3":"51.102","4":"2.077","5":"0.878"},{"1":"26","2":"2.686","3":"56.870","4":"2.265","5":"0.421"},{"1":"27","2":"2.114","3":"49.875","4":"2.037","5":"0.077"},{"1":"28","2":"2.106","3":"73.397","4":"2.804","5":"-0.698"},{"1":"29","2":"4.413","3":"65.243","4":"2.538","5":"1.875"},{"1":"30","2":"1.886","3":"46.686","4":"1.933","5":"-0.047"},{"1":"31","2":"3.102","3":"54.310","4":"2.182","5":"0.920"},{"1":"32","2":"1.263","3":"46.784","4":"1.937","5":"-0.674"},{"1":"33","2":"4.741","3":"60.730","4":"2.391","5":"2.350"},{"1":"34","2":"3.240","3":"49.644","4":"2.030","5":"1.211"},{"1":"35","2":"1.082","3":"47.199","4":"1.950","5":"-0.869"},{"1":"36","2":"3.395","3":"58.875","4":"2.331","5":"1.064"},{"1":"37","2":"0.431","3":"55.173","4":"2.210","5":"-1.779"},{"1":"38","2":"1.283","3":"58.633","4":"2.323","5":"-1.040"},{"1":"39","2":"1.937","3":"44.929","4":"1.876","5":"0.061"},{"1":"40","2":"3.302","3":"53.053","4":"2.141","5":"1.161"},{"1":"41","2":"3.136","3":"43.716","4":"1.837","5":"1.299"},{"1":"42","2":"0.753","3":"53.875","4":"2.168","5":"-1.415"},{"1":"43","2":"2.384","3":"63.383","4":"2.478","5":"-0.094"},{"1":"44","2":"1.903","3":"60.708","4":"2.390","5":"-0.487"},{"1":"45","2":"1.725","3":"66.155","4":"2.568","5":"-0.843"},{"1":"46","2":"3.818","3":"59.068","4":"2.337","5":"1.481"},{"1":"47","2":"2.037","3":"39.552","4":"1.701","5":"0.336"},{"1":"48","2":"1.122","3":"58.080","4":"2.305","5":"-1.183"},{"1":"49","2":"0.267","3":"55.690","4":"2.227","5":"-1.960"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Obtenemos los resultados del modelo para cada observación, o sea cada fila de nuestro dataframe original. La columna que buscamos está al final (<code>residual</code>). También tenemos</p>
<ul>
<li><code>crimenes_odio_prom_100k_fbi</code>: El valor observado en los datos que usamos para el modelo, para la variable que intentamos predecir; es el valor de <span class="math inline">\(y\)</span></li>
<li><code>mediana_ingreso_hogares</code>: El valor que toma la variable predictora, alias <span class="math inline">\(x\)</span></li>
<li><code>crimenes_odio_prom_100k_fbi_hat</code>: Este es el valor que “predice” el modelo, alias “y con sombrerito” (de ahí lo de <em>hat</em>), o <span class="math inline">\(\hat{y}\)</span></li>
<li><code>residual</code>: y por fin los residuos, la diferencia <span class="math inline">\(y - \hat{y}\)</span> para cada fila.</li>
</ul>
<p>Podemos notar que en algunos casos el error / residuo / desvío es bastante grande, en relación a la magnitud de la variable a predecir. Esto era esperable dada la débil correlación entre variables.</p>
<p>Siempre podemos esperar una cierta divergencia entre las predicciones y los valores observados, por lo que los residuos siempre tendrán (en general) un valor distinto a cero. Pero es importante que los residuos se distribuyan al azar, sin indicios de <em>patrones sistemáticos</em>. Si así fuere, podemos considerar que nuestro modelo es adecuado.</p>
<p>¿Cómo determinamos que no exhiben patrones sistemáticos? Una vez mas, se trata de una evaluación bastante subjetiva, y cada quien estará conforme dependiendo del contexto y la experiencia previa. Aún así podemos argumentar en favor de la adecuación del modelo cuando:</p>
<ol style="list-style-type: decimal">
<li>El promedio de los residuos se aproxima a cero; es decir, que los residuos positivos se cancelan con los negativos, promediando cerca de cero.</li>
<li>El valor de los residuos no depende del valor de <span class="math inline">\(x\)</span>; es decir, no se observa un crecimiento (o decrecimiento) sistemático de la magnitud de los residuos a medida que<span class="math inline">\(x\)</span> crece</li>
</ol>
<p>Veamos si nuestro modelo cumple con <code>1.</code>, calculando el promedio de los residuos:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="modelado-estadístico.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(residuos_regresion<span class="sc">$</span>residual)</span></code></pre></div>
<pre><code>## [1] 0.00002040816</code></pre>
<p>Dio un resultado infinitesimal, cercano a 0, así que condición cumplida.</p>
<div class="tip">
<p>Es probable que al ejecutar la línea de código el resultado aparezca expresado en notación científica: <code>2.040816e-05</code>, que significa <span class="math inline">\(2.040816 * 10^{-5}\)</span>. En palabras, “2.040816 multiplicado por 10 elevado a la potencia -5”. Lo cual efectivamente es 0.00002040816.</p>
<p>Por defecto, R utiliza notación científica para representar de forma compacta los números con muchos espacios decimales. Si -como la mayoría de los seres humanos- estamos poco acostumbrados a ese formato, podemos desactivarlo ejecutando esta línea: <code>options(scipen = 999)</code>. Esto hace que R se abstenga de usarlo por el resto de la sesión de trabajo. Podemos comprobarlo ejecutando una vez más la línea de código que calcula el promedio, y el resultado saldrá en todo su esplendor de espacios decimales.</p>
</div>
<p>¿Y que pasa con <code>2.</code>, la magnitud de los residuos sin crecer ni decrecer de forma notable a medida que se incrementa la variable predictora? Veamoslo en un gráfico de dispersión:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="modelado-estadístico.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residuos_regresion) <span class="sc">+</span></span>
<span id="cb25-2"><a href="modelado-estadístico.html#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> mediana_ingreso_hogares, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="modelado-estadístico.html#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mediana del ingreso de hogares&quot;</span>, <span class="at">y =</span> <span class="st">&quot;residuo del modelo lineal&quot;</span>)</span></code></pre></div>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>No se ve una “rampa” ascendente o descendente de los residuos a medida que aumenta la variable de ingresos, así que condición cumplida.</p>
</div>
<div id="cómo-estamos-de-confianza" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> ¿Cómo estamos de confianza?<a href="modelado-estadístico.html#cómo-estamos-de-confianza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>¿Ya estamos parra considerar que el modelo útil, o al menos “significativo”, que aporta evidencia para considerar que hay una relación entre nuestras dos variables?</p>
<p>Falta un chequeo más, y más importante aún. Es el de evaluar que tanta certeza, o confianza, tenemos en que hay una correlación entre estas variables en la vida real, más allá de la que se ve en los datos que tenemos disponibles. Para eso recurrimos al llamado <em>intervalo de confianza</em>. Volvamos a revisar la tabla con los estimados de nuestro modelo:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="modelado-estadístico.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(modelo_ingresos)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["lower_ci"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["upper_ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"intercept","2":"0.412","3":"1.054","4":"0.391","5":"0.698","6":"-1.708","7":"2.532"},{"1":"mediana_ingreso_hogares","2":"0.033","3":"0.019","4":"1.711","5":"0.094","6":"-0.006","7":"0.071"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>El efecto estimado de “mediana_ingreso_hogares” es de 0.033, un números positivo. Esto indica que cuando esa variable predictora crece, también crece la variable a predecir -la tasa de crímenes-. Pero en todo análisis estadístico siempre hay una incertidumbre. Una forma de cuantificarla es con un rango de valores, llamado intervalo de confianza. El rango incluye al valor estimado para el efecto, que es el más probable, pero nos recuerda que no tenemos certeza absoluta de que ese número sea exacto, es sólo una aproximación. Por eso ofrece un valor mínimo que sería razonable, y un valor máximo: los vemos en las columnas <code>lower_ci</code> y <code>upper_ci</code>.</p>
<p>Y aquí la mala noticia: si revisamos los valores para nuestra variable predictora, vemos que su estimado máximo es 0.071 y su mínimo es -0,006. ¡Un valor negativo! Esto implica que, aún cuando el estimado más probable es un efecto positivo, cabe dentro del rango de valores razonables que el efecto sea 0, o sea nada. E incluso ligeramente negativo, cambiando el sentido de lo que nos indica el estimado del modelo.</p>
<p>Cuando ocurre esto, que el intervalo de confianza pasa por el cero, decimos que nuestro modelo no es estadísticamente signifcativo. O sea, no aporta evidencia acerca de la relación entre variables que estamos investigando. Pero a no ponernos tristes: esto es normal, y útil, porque nos permite verificar nuestras hipótesis de trabajo.</p>
</div>
<div id="regresión-con-una-variable-categórica" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Regresión con una variable categórica<a href="modelado-estadístico.html#regresión-con-una-variable-categórica" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El dataset de crímenes de odio no incluye variables categóricas además de la de estado. Pero podemos crearnos una con facilidad: “¿Ganó Donald Trump en las elecciones presidenciales de 2016?”. Para sumar esta variable podemos usar <code>mutate()</code> para sumar una columna, y como contenido asignarle el resultado de evaluar si Trump obtuvo al menos el 47% de los votos. Es un umbral de corte definido revisando los <a href="https://www.nytimes.com/elections/2016/results/president">resultados</a> de aquella elección, nada riguroso pero servirá para practicar ahora:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="modelado-estadístico.html#cb27-1" aria-hidden="true" tabindex="-1"></a>crimenes_odio <span class="ot">&lt;-</span> crimenes_odio <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="modelado-estadístico.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">&quot;trump_electo&quot;</span> <span class="ot">=</span> pct_votantes_trump <span class="sc">&gt;</span> <span class="dv">46</span>)</span></code></pre></div>
<p>Esto nos da una columna <code>trump_electo</code> de tipo “logical”. Es decir que contiene “cierto” o “falso” (<code>TRUE</code> o <code>FALSE</code>). Una variable dicotómica, que cae dentro del tipo categórico.</p>
<p>Comencemos por explorar los datos con una visualización.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="modelado-estadístico.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> crimenes_odio) <span class="sc">+</span></span>
<span id="cb28-2"><a href="modelado-estadístico.html#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> trump_electo, </span>
<span id="cb28-3"><a href="modelado-estadístico.html#cb28-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> crimenes_odio_prom_100k_fbi, </span>
<span id="cb28-4"><a href="modelado-estadístico.html#cb28-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> trump_electo)) </span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Se vislumbra que una menor tasa de crímenes de odio parece estar asociada a los estados donde Trump ganó la elección en 2016. Eso si, la profusión de puntos hace que muchos terminen superpuestos, haciendo imposible determinar cuántos ocupan cada posición (un problema llamado <em>overplotting</em> en inglés). Una variante de <code>geom_point()</code> llamada <code>geom_jitter()</code> resuelve este problema al “sacudir” los puntos, sumando a cada uno un pequeño valor al azar para que se separe de los que comparten su posición. Es un buen ejemplo de la paradoja por la cual reducir la precisión de la información a veces permite entender mejor lo que está ocurriendo. Usamos <code>geom_jitter()</code> igual que <code>geom_point()</code>:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="modelado-estadístico.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> crimenes_odio) <span class="sc">+</span></span>
<span id="cb30-2"><a href="modelado-estadístico.html#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> trump_electo, </span>
<span id="cb30-3"><a href="modelado-estadístico.html#cb30-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> crimenes_odio_prom_100k_fbi, </span>
<span id="cb30-4"><a href="modelado-estadístico.html#cb30-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> trump_electo))</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Algún ojo avizor habrá notado que la clasificación por color no es necesaria, ya que el resultado de la elección está señalado por la posición en el eje de las <code>x</code>. El color cumple aquí una función más que nada cosmética, en pos de hacer al gráfico maś atractivo a la vista.</p>
<p>Otra forma de visualizar la diferencia es con un histograma, facetado por la variable “trump_electo”:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="modelado-estadístico.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crimenes_odio) <span class="sc">+</span></span>
<span id="cb32-2"><a href="modelado-estadístico.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(crimenes_odio_prom_100k_fbi, <span class="at">fill =</span> trump_electo)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="modelado-estadístico.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> trump_electo)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Aquí vemos que en los estados donde Trump resultó electo es más frecuente una tasa baja de crímenes, incluso menores a 1 cada 100.000 (valores mínimos que no se alcanzan en la otra categoría.)</p>
<p>Bien, parece haber una relación entre resultados electorales y crímenes de odio, aunque no la hemos cuantificado. Para eso, recurrimos a una regresión lineal con variable explicativa categórica. Se obtiene de la misma manera que antes, no hay cambios en la forma de invocar <code>lm()</code> por el hecho de que la variable ahora sea categórica en vez de numérica.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="modelado-estadístico.html#cb35-1" aria-hidden="true" tabindex="-1"></a>modelo_eleccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(crimenes_odio_prom_100k_fbi <span class="sc">~</span> trump_electo, <span class="at">data =</span> crimenes_odio)</span>
<span id="cb35-2"><a href="modelado-estadístico.html#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="modelado-estadístico.html#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="modelado-estadístico.html#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(modelo_eleccion)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["lower_ci"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["upper_ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"intercept","2":"2.639","3":"0.273","4":"9.661","5":"0.000","6":"2.089","7":"3.188"},{"1":"trump_electoTRUE","2":"-0.705","3":"0.343","4":"-2.054","5":"0.046","6":"-1.396","7":"-0.014"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>¿Qué ocurrió aquí? <code>lm()</code> inspeccionó el contenido de la variable “trump_electo” y encontró dos niveles o categorías (<code>TRUE</code> y <code>FALSE</code>). Tomó el primero en orden alfabético, “FALSE”, como línea de base. La intersección (<em>intercept</em>) de la regresión es el promedio de crímenes cada 100.000 habitantes para los estados donde Trumpo no ganó la elección -donde es <code>FALSE</code> ese hecho.</p>
<p>Para la categoría restante, el estimado representa la diferencia respecto a la línea de base: para un esatdo donde Trump si fue electo (“TRUE”), podemos esperar -en promedio- una tasa menor en 0.705 unidades.</p>
<p>Prestemos atención a los residuos.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="modelado-estadístico.html#cb36-1" aria-hidden="true" tabindex="-1"></a>residuos_modelo_eleccion <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(modelo_eleccion)</span>
<span id="cb36-2"><a href="modelado-estadístico.html#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="modelado-estadístico.html#cb36-3" aria-hidden="true" tabindex="-1"></a>residuos_modelo_eleccion</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["ID"],"name":[1],"type":["int"],"align":["right"]},{"label":["crimenes_odio_prom_100k_fbi"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["trump_electo"],"name":[3],"type":["lgl"],"align":["right"]},{"label":["crimenes_odio_prom_100k_fbi_hat"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["residual"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"1.806","3":"TRUE","4":"1.933","5":"-0.127"},{"1":"2","2":"1.657","3":"TRUE","4":"1.933","5":"-0.277"},{"1":"3","2":"3.414","3":"TRUE","4":"1.933","5":"1.481"},{"1":"4","2":"0.869","3":"TRUE","4":"1.933","5":"-1.064"},{"1":"5","2":"2.398","3":"FALSE","4":"2.639","5":"-0.241"},{"1":"6","2":"2.805","3":"FALSE","4":"2.639","5":"0.166"},{"1":"7","2":"3.773","3":"FALSE","4":"2.639","5":"1.134"},{"1":"8","2":"1.470","3":"FALSE","4":"2.639","5":"-1.169"},{"1":"9","2":"0.698","3":"TRUE","4":"1.933","5":"-1.235"},{"1":"10","2":"0.412","3":"TRUE","4":"1.933","5":"-1.521"},{"1":"11","2":"1.891","3":"TRUE","4":"1.933","5":"-0.042"},{"1":"12","2":"1.044","3":"FALSE","4":"2.639","5":"-1.595"},{"1":"13","2":"1.757","3":"TRUE","4":"1.933","5":"-0.176"},{"1":"14","2":"0.561","3":"TRUE","4":"1.933","5":"-1.372"},{"1":"15","2":"2.144","3":"TRUE","4":"1.933","5":"0.211"},{"1":"16","2":"4.208","3":"TRUE","4":"1.933","5":"2.275"},{"1":"17","2":"1.341","3":"TRUE","4":"1.933","5":"-0.592"},{"1":"18","2":"2.627","3":"FALSE","4":"2.639","5":"-0.012"},{"1":"19","2":"1.325","3":"FALSE","4":"2.639","5":"-1.314"},{"1":"20","2":"4.802","3":"FALSE","4":"2.639","5":"2.163"},{"1":"21","2":"3.200","3":"TRUE","4":"1.933","5":"1.267"},{"1":"22","2":"3.612","3":"FALSE","4":"2.639","5":"0.974"},{"1":"23","2":"0.623","3":"TRUE","4":"1.933","5":"-1.311"},{"1":"24","2":"1.909","3":"TRUE","4":"1.933","5":"-0.024"},{"1":"25","2":"2.955","3":"TRUE","4":"1.933","5":"1.022"},{"1":"26","2":"2.686","3":"TRUE","4":"1.933","5":"0.753"},{"1":"27","2":"2.114","3":"FALSE","4":"2.639","5":"-0.525"},{"1":"28","2":"2.106","3":"TRUE","4":"1.933","5":"0.173"},{"1":"29","2":"4.413","3":"FALSE","4":"2.639","5":"1.775"},{"1":"30","2":"1.886","3":"FALSE","4":"2.639","5":"-0.752"},{"1":"31","2":"3.102","3":"FALSE","4":"2.639","5":"0.464"},{"1":"32","2":"1.263","3":"TRUE","4":"1.933","5":"-0.671"},{"1":"33","2":"4.741","3":"TRUE","4":"1.933","5":"2.808"},{"1":"34","2":"3.240","3":"TRUE","4":"1.933","5":"1.307"},{"1":"35","2":"1.082","3":"TRUE","4":"1.933","5":"-0.852"},{"1":"36","2":"3.395","3":"FALSE","4":"2.639","5":"0.756"},{"1":"37","2":"0.431","3":"TRUE","4":"1.933","5":"-1.502"},{"1":"38","2":"1.283","3":"FALSE","4":"2.639","5":"-1.356"},{"1":"39","2":"1.937","3":"TRUE","4":"1.933","5":"0.004"},{"1":"40","2":"3.302","3":"TRUE","4":"1.933","5":"1.368"},{"1":"41","2":"3.136","3":"TRUE","4":"1.933","5":"1.203"},{"1":"42","2":"0.753","3":"TRUE","4":"1.933","5":"-1.181"},{"1":"43","2":"2.384","3":"TRUE","4":"1.933","5":"0.451"},{"1":"44","2":"1.903","3":"FALSE","4":"2.639","5":"-0.735"},{"1":"45","2":"1.725","3":"FALSE","4":"2.639","5":"-0.914"},{"1":"46","2":"3.818","3":"FALSE","4":"2.639","5":"1.179"},{"1":"47","2":"2.037","3":"TRUE","4":"1.933","5":"0.104"},{"1":"48","2":"1.122","3":"TRUE","4":"1.933","5":"-0.811"},{"1":"49","2":"0.267","3":"TRUE","4":"1.933","5":"-1.666"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Calculemos el promedio de los residuos, para verificar que están cerca del cero,</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="modelado-estadístico.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(residuos_modelo_eleccion<span class="sc">$</span>residual)</span></code></pre></div>
<pre><code>## [1] 0.00002040816</code></pre>
<p>y grafiquemos su dispersion de acuerdo a l categoría que les toca, para ver si es similar:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="modelado-estadístico.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residuos_modelo_eleccion) <span class="sc">+</span></span>
<span id="cb39-2"><a href="modelado-estadístico.html#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> trump_electo, <span class="at">y =</span> residual, <span class="at">color =</span> trump_electo)) <span class="sc">+</span></span>
<span id="cb39-3"><a href="modelado-estadístico.html#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Trump electo en 2016&quot;</span>, <span class="at">y =</span> <span class="st">&quot;residuo del modelo lineal&quot;</span>)</span></code></pre></div>
<p><img src="CD_AJ_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Notamos que:</p>
<ol style="list-style-type: decimal">
<li>Los residuos tienen un promedio cercano a cero, o sea que están repartidos en forma pareja entre positivos y negativos. Condición cumplida.</li>
<li>La dispersión no crece ni decrece en forma drástica en categorías distintas, rasgo de un buen modelo. Esto es un poco subjetivo -lo evaluamos a ojo- pero damos por cumplida la condición.</li>
</ol>
<p>Ahora vamos al veredicto final: ¿Es estadísticamente significativo el resultado?</p>
<p>Prestemos atención al intervalo de confianza, dado por las columnas <code>lower_ci</code> y <code>upper_ci</code></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="modelado-estadístico.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(modelo_eleccion)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["lower_ci"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["upper_ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"intercept","2":"2.639","3":"0.273","4":"9.661","5":"0.000","6":"2.089","7":"3.188"},{"1":"trump_electoTRUE","2":"-0.705","3":"0.343","4":"-2.054","5":"0.046","6":"-1.396","7":"-0.014"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>El intervalo no pasa por el cero! El rango va de -1,396 a -0,014. Por tenue que pueda llegar a ser, tenemos confianza en que habrá algún efecto.</p>
<p>¡Hemos realizado un modelo estadísticamente significativo!</p>
</div>
</div>
<div id="regresión-con-múltiples-variables" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Regresión con múltiples variables<a href="modelado-estadístico.html#regresión-con-múltiples-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hasta aquí hemos usado la regresión lineal para hacer explícita la relación entre una variable <em>resultante</em> <span class="math inline">\(y\)</span> y una única variable <em>predictiva</em> o <em>explicativa</em> <span class="math inline">\(x\)</span>. En algunos de nuestros resultados pudimos intuir que el agregado de alguna variable explicativa adicional podría mejorar nuestras predicciones. De eso se trata la regresión lineal múltiple: incorporar una cantidad arbitraria de variables al modelo, buscando representar las múltiples dinámicas que inciden en el fenómeno estudiado.</p>
<p>Una buena noticia es que, en general, agregar variables a nuestro modelo estadístico no requiere mucho esfuerzo adicional. En la época en que los cálculos matemáticos debían hacerse sin la ayuda de una computadora, sumar variables sin ton ni son debía tener poca gracia, debido a la creciente cantidad de cálculos a resolver. Para nosotros que dejamos la tarea en manos de software especializado, el problema es el opuesto. Es tan fácil sumar variables al modelo, que debemos evitar la tentación de arrojar todo dentro de la fórmula de regresión lineal y decidir luego que parece importante y que no.</p>
<p>Aclarado eso, en este caso tenemos un dataset en el que las variables han sido elegidas precisamente por su potencial para afectar el fenómeno a estudiar. Por eso podemos incluir todas las variables un modelo complejo, asumiendo que el nivel de ingresos, el porcentaje de desocupados, el de habitantes indocumentados, etc. pueden explicar en alguna medida la incidencia de crímenes de odio.</p>
<p>Vamos a modelar el promedio 2010-2016 de crímenes de odio cada 100.000 habitantes, como resultante de todas las variables disponibles excepto “estado” y “crimenes_odio_100k_splc”. Esta última debido a que se parece mucho a la variable que queremos predecir -con seguridad estan estrechamente relacionadas-, por lo cual es de esperarse que si la agregamos al modelo nos de una altísima correlación, pero sin mucho valor: ya lo sabíamos. También vamos a dejar fuera a la variable “trump_electo”, ya que no es otra cosa que una versión simplificada, con menos información, de la variable de porcentaje de electores.</p>
<p>Pasando a la práctica, la única diferencia respecto a una regresión lineal simple es que usamos <code>+</code> para agregar variables en la fórmula de <code>lm()</code>:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="modelado-estadístico.html#cb41-1" aria-hidden="true" tabindex="-1"></a>modelo_mult <span class="ot">&lt;-</span> <span class="fu">lm</span>(crimenes_odio_prom_100k_fbi <span class="sc">~</span> </span>
<span id="cb41-2"><a href="modelado-estadístico.html#cb41-2" aria-hidden="true" tabindex="-1"></a>                    mediana_ingreso_hogares <span class="sc">+</span> pct_desocupados <span class="sc">+</span> pct_reside_area_metro <span class="sc">+</span></span>
<span id="cb41-3"><a href="modelado-estadístico.html#cb41-3" aria-hidden="true" tabindex="-1"></a>                    pct_secundaria_completa <span class="sc">+</span> pct_no_ciudadanos <span class="sc">+</span> pct_pobreza_blancos <span class="sc">+</span> </span>
<span id="cb41-4"><a href="modelado-estadístico.html#cb41-4" aria-hidden="true" tabindex="-1"></a>                    indice_gini <span class="sc">+</span> pct_no_blancos <span class="sc">+</span> pct_votantes_trump,</span>
<span id="cb41-5"><a href="modelado-estadístico.html#cb41-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> crimenes_odio)</span></code></pre></div>
<p>Veamos la tabla con los resultados:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="modelado-estadístico.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(modelo_mult)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std_error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["lower_ci"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["upper_ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"intercept","2":"-24.063","3":"15.951","4":"-1.509","5":"0.140","6":"-56.413","7":"8.288"},{"1":"mediana_ingreso_hogares","2":"0.043","3":"0.043","4":"0.985","5":"0.331","6":"-0.045","7":"0.130"},{"1":"pct_desocupados","2":"0.179","3":"0.230","4":"0.778","5":"0.441","6":"-0.287","7":"0.645"},{"1":"pct_reside_area_metro","2":"-0.002","3":"0.017","4":"-0.138","5":"0.891","6":"-0.036","7":"0.032"},{"1":"pct_secundaria_completa","2":"0.123","3":"0.116","4":"1.058","5":"0.297","6":"-0.113","7":"0.359"},{"1":"pct_no_ciudadanos","2":"0.232","3":"0.109","4":"2.141","5":"0.039","6":"0.012","7":"0.453"},{"1":"pct_pobreza_blancos","2":"0.165","3":"0.143","4":"1.151","5":"0.257","6":"-0.126","7":"0.456"},{"1":"indice_gini","2":"23.068","3":"15.123","4":"1.525","5":"0.136","6":"-7.602","7":"53.739"},{"1":"pct_no_blancos","2":"-0.045","3":"0.024","4":"-1.836","5":"0.075","6":"-0.094","7":"0.005"},{"1":"pct_votantes_trump","2":"0.013","3":"0.029","4":"0.465","5":"0.645","6":"-0.045","7":"0.072"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>¿Cómo interpretamos esos resultados? Más o menos de la misma manera que con la regresión simple. Como antes, tenemos un coeficiente para la intersección, al que no prestamos mucha atención porque no nos dice nada de la relación entre las variables. Lo que cambia es que esta vez tenemos muchas variables predictoras en lugar de una, cada una con su estimado Los estimados positivos indican que la relación entre la variable predictora y la resultante es de correlación positiva (cuando una crece la otra tiende a crecer también) y lo opuesto para los estimados negativos.</p>
<p>Pero vayamos a lo que ya sabemos que es muy importante: ¿Alguno de estos estimados es estadísticamente significativo? Si prestamos atención a las columnas del intervalo de confianza, vemos que sólo “pct_no_ciudadanos” tiene un rango que no pasa por el cero: su mínimo y su máximo son positivos. Al estimar el efecto de todas estas variables juntas -o como suele decirse, “controlando” por todas estas variables- el porcentaje de residentes sin ciudadanía es la única con efecto significativo.</p>
<p>Notemos que el porcentaje de votantes de Trump, que en un modelo simple había sido una variable significativa, ahora ya no lo es. A eso se le llama controlar por una variable: Otra forma de decirlo es que “controlando por el porcentaje de población sin ciudadanía” el voto a Trump no tiene efecto significativo en la incidencia de crímenes de odio.</p>
<p>Para <em>narrar</em> estos resultados, podemos intentar algo así:</p>
<ul>
<li>Cuando las demás variables se mantienen constantes (es decir, en estados con atributos similares en ingresos, desocupación, índice Gini, etc.) con el incremento de una unidad en el porcentaje de residentes indocumentados es esperable un incremento de 0,232 crímenes de odio en el promedio interanual cada 100.000 habitantes.</li>
</ul>
<p>Pensemos un poco si esto tienen sentido. La correlación positiva entre presencia de población migrante o en situación irregular y crímenes de odio es esperable si asumimos que este grupo suele ser el más vulnerable a los crímenes de odio. Por otra parte, quizás tenga tanto sentido como para ser algo obvio. En ese caso, ¡no hemos descubierto nada trascendental! Pero tampoco se le puede pedir tanto a un ejercicio.</p>
<p>Quedan muchos más datos para explorar, hipótesis para comprobar, e interrelaciones para revelar.</p>
</div>
<div id="ejercicios-5" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Ejercicios<a href="modelado-estadístico.html#ejercicios-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I. En base a un dataset de nuestra preferencia, mostremos la relación entre dos variables continuas o numéricas usando un gráfico de dispersión (vía <code>geom_point()</code>) y expliquemos lo que muestra el gráfico. Vale usar el dataset que hemos presentado en este capítulo, pero tendrá mucha más gracia jugar con algún otro.</p>
<ol start="2" style="list-style-type: upper-roman">
<li><p>Realicemos un modelo de regresión lineal para esas dos variables. Describamos los resultados, ofreciendo una interpretación.</p></li>
<li><p>Mostremos la relación entre una variables categórica y otra continua/numérica, con un gráfico <em>boxplot</em> (mediante <code>geom_boxplot()</code>) o un gráfico de puntos “sacudidos” (mediante <code>geom_jitter()</code>). Expliquemos lo que muestra el gráfico.</p></li>
<li><p>Realicemos un modelo de regresión lineal para esas dos variables, describiendo los resultados sin olvidar interpretarlos.</p></li>
</ol>
<p>V. Realicemos una regresión lineal con la variable a predecir de I o III, junto con otras adicionales. Es decir, realizar una regresión con múltiples variables predictoras. Describamos los resultados, interpretándolos. ¿En qué cambian respecto al modelo que usa sólo un predictor?</p>
<hr />
<p>Con eso cerramos el capítulo, y el manual.</p>
<p>Esperamos haber provisto una introducción satisfactoria al análisis, modelado y visualización de información, y que haya sido tan sólo el inicio de un largo y gratificante recorrido.</p>
<p>¡Gracias por haber llegado hasta aquí!</p>

</div>
</div>






<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Véase Aires, Ian “Venta de Autos justa. La discriminación de género y raza en las negociaciones de venta de autos”, 1991, versión en español en Ian Ayres, <em>La discriminación en el Mercado</em> Univ. Palermo, Buenos Aires, 2012<a href="modelado-estadístico.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="trabajando-con-datos-espaciales-y-temporales.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CD_AJ.pdf", "CD_AJ.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
