<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Poniendo los datos en forma | Ciencia de Datos para Activismo Jurídico</title>
  <meta name="description" content="3 Poniendo los datos en forma | Ciencia de Datos para Activismo Jurídico" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Poniendo los datos en forma | Ciencia de Datos para Activismo Jurídico" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="bitsandbricks/CD_AJ" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Poniendo los datos en forma | Ciencia de Datos para Activismo Jurídico" />
  
  
  

<meta name="author" content="Antonio Vazquez Brust" />
<meta name="author" content="Demian Zayat" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="una-presentación-a-toda-marcha-de-r.html"/>
<link rel="next" href="visualización.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ciencia de Datos para Activismo Jurídico</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>¿Para quién es esto?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#antes-de-empezar"><i class="fa fa-check"></i>Antes de empezar</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="qué-es-la-ciencia-de-datos.html"><a href="qué-es-la-ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> ¿Qué es la ciencia de datos?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="qué-es-la-ciencia-de-datos.html"><a href="qué-es-la-ciencia-de-datos.html#qué-significa-hacer-ciencia-de-datos"><i class="fa fa-check"></i><b>1.1</b> ¿Qué significa hacer ciencia de datos?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html"><i class="fa fa-check"></i><b>2</b> Una presentación a toda marcha de R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#nuestro-primer-proyecto-en-r"><i class="fa fa-check"></i><b>2.1</b> Nuestro primer proyecto en R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#a-investigar-cual-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><i class="fa fa-check"></i><b>2.1.1</b> A investigar: ¿Cual es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
<li class="chapter" data-level="2.1.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#crear-un-proyecto-en-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Crear un proyecto en RStudio</a></li>
<li class="chapter" data-level="2.1.3" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#escribiendo-un-script"><i class="fa fa-check"></i><b>2.1.3</b> Escribiendo un script</a></li>
<li class="chapter" data-level="2.1.4" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#cargar-los-datos"><i class="fa fa-check"></i><b>2.1.4</b> Cargar los datos</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#visualización-la-exploración-gráfica-de-la-información"><i class="fa fa-check"></i><b>2.2</b> Visualización: la exploración gráfica de la información</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#haciendo-mapas"><i class="fa fa-check"></i><b>2.2.1</b> Haciendo mapas</a></li>
<li class="chapter" data-level="2.2.2" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#agregando-datos"><i class="fa fa-check"></i><b>2.2.2</b> Agregando datos</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#el-veredicto-final"><i class="fa fa-check"></i><b>2.3</b> El veredicto final</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#cuál-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><i class="fa fa-check"></i><b>2.3.1</b> ¿Cuál es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="una-presentación-a-toda-marcha-de-r.html"><a href="una-presentación-a-toda-marcha-de-r.html#ejercicios"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html"><i class="fa fa-check"></i><b>3</b> Poniendo los datos en forma</a>
<ul>
<li class="chapter" data-level="3.1" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#primeros-pasos-al-examinar-un-conjunto-de-datos-nuevo"><i class="fa fa-check"></i><b>3.1</b> Primeros pasos al examinar un conjunto de datos nuevo</a></li>
<li class="chapter" data-level="3.2" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#cruzando-variables-la-operación-join"><i class="fa fa-check"></i><b>3.2</b> Cruzando variables: la operación <code>join</code></a></li>
<li class="chapter" data-level="3.3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#transformando-los-datos"><i class="fa fa-check"></i><b>3.3</b> Transformando los datos</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#seleccionar-columnas-con-select"><i class="fa fa-check"></i><b>3.3.1</b> Seleccionar columnas con <code>select()</code></a></li>
<li class="chapter" data-level="3.3.2" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#filtrar-filas-con-filter"><i class="fa fa-check"></i><b>3.3.2</b> Filtrar filas con <code>filter()</code></a></li>
<li class="chapter" data-level="3.3.3" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#ordenar-filas-con-arrange"><i class="fa fa-check"></i><b>3.3.3</b> Ordenar filas con <code>arrange()</code></a></li>
<li class="chapter" data-level="3.3.4" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#agregar-nuevas-variables-con-mutate"><i class="fa fa-check"></i><b>3.3.4</b> Agregar nuevas variables con <code>mutate()</code></a></li>
<li class="chapter" data-level="3.3.5" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#extraer-sumarios-con-summarise"><i class="fa fa-check"></i><b>3.3.5</b> Extraer sumarios con <code>summarise()</code></a></li>
<li class="chapter" data-level="3.3.6" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#bonus-el-operador-pipe"><i class="fa fa-check"></i><b>3.3.6</b> ¡BONUS! El operador “pipe”: <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="poniendo-los-datos-en-forma.html"><a href="poniendo-los-datos-en-forma.html#ejercicios-1"><i class="fa fa-check"></i><b>3.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualización.html"><a href="visualización.html"><i class="fa fa-check"></i><b>4</b> Visualización</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visualización.html"><a href="visualización.html#una-buena-visualización-para-empezar-el-scatterplot"><i class="fa fa-check"></i><b>4.1</b> Una buena visualización para empezar: el <em>scatterplot</em></a></li>
<li class="chapter" data-level="4.2" data-path="visualización.html"><a href="visualización.html#ajustando-color-y-tamaño"><i class="fa fa-check"></i><b>4.2</b> Ajustando color y tamaño</a></li>
<li class="chapter" data-level="4.3" data-path="visualización.html"><a href="visualización.html#facetado"><i class="fa fa-check"></i><b>4.3</b> Facetado</a></li>
<li class="chapter" data-level="4.4" data-path="visualización.html"><a href="visualización.html#gráficos-de-barras"><i class="fa fa-check"></i><b>4.4</b> Gráficos de barras</a></li>
<li class="chapter" data-level="4.5" data-path="visualización.html"><a href="visualización.html#histogramas"><i class="fa fa-check"></i><b>4.5</b> Histogramas</a></li>
<li class="chapter" data-level="4.6" data-path="visualización.html"><a href="visualización.html#preparando-una-visualización-para-compartir"><i class="fa fa-check"></i><b>4.6</b> Preparando una visualización para compartir</a></li>
<li class="chapter" data-level="4.7" data-path="visualización.html"><a href="visualización.html#otras-visualizaciones"><i class="fa fa-check"></i><b>4.7</b> Otras visualizaciones</a></li>
<li class="chapter" data-level="4.8" data-path="visualización.html"><a href="visualización.html#ejercicios-2"><i class="fa fa-check"></i><b>4.8</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html"><i class="fa fa-check"></i><b>5</b> Analisis de texto</a>
<ul>
<li class="chapter" data-level="5.1" data-path="analisis-de-texto.html"><a href="analisis-de-texto.html#ejercicios-3"><i class="fa fa-check"></i><b>5.1</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html"><i class="fa fa-check"></i><b>6</b> Información geográfica y mapas</a>
<ul>
<li class="chapter" data-level="6.1" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#los-datos-georreferenciados"><i class="fa fa-check"></i><b>6.1</b> Los datos georreferenciados</a></li>
<li class="chapter" data-level="6.2" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#formatos-de-archivo"><i class="fa fa-check"></i><b>6.2</b> Formatos de archivo</a></li>
<li class="chapter" data-level="6.3" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#explorando-un-archivo-con-información-geográfica"><i class="fa fa-check"></i><b>6.3</b> Explorando un archivo con información geográfica</a></li>
<li class="chapter" data-level="6.4" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#visualizando-información-geográfica"><i class="fa fa-check"></i><b>6.4</b> Visualizando información geográfica</a></li>
<li class="chapter" data-level="6.5" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#volcando-en-el-mapa-información-de-múltiples-fuentes"><i class="fa fa-check"></i><b>6.5</b> Volcando en el mapa información de múltiples fuentes</a></li>
<li class="chapter" data-level="6.6" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#combinando-capas-geográficas"><i class="fa fa-check"></i><b>6.6</b> Combinando capas geográficas</a></li>
<li class="chapter" data-level="6.7" data-path="información-geográfica-y-mapas.html"><a href="información-geográfica-y-mapas.html#ejercicios-4"><i class="fa fa-check"></i><b>6.7</b> Ejercicios</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ciencia de Datos para Activismo Jurídico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="poniendo-los-datos-en-forma" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Poniendo los datos en forma</h1>
<p><img src="imagenes/amasando.jpg" width="100%" /></p>
<p>Cómo ya hemos mencionado, es normal que la mayor parte del tiempo dedicado a un proyecto de análisis se nos vaya en la limpieza y orden de los datos disponibles. Aún cuando nuestros datos provengan de fuentes oficiales (un gobierno nacional, el Banco Mundial, etc) en muy rara ocasión podremos usarlos para nuestros fines sin antes procesarlos. Y aún si los datos llegaran en perfectas condiciones, no tenemos forma de saberlo hasta haber realizado una exploración para verificarlo.</p>
<p>Ésta inevitable etapa de preparación es llamada <em>data wrangling</em> en inglés, algo así como el proceso de “domar los datos”. El término hace referencia, en clave de humor, al esfuerzo que requiere la puesta en orden cuando los datos son cuantiosos, de muchas fuentes distintas, o en particular desprolijos. Para que la experiencia sea lo menos tediosa posible, y podamos pasar rápido al momento de extraer conocimiento, vamos a practicar algunas técnicas muy útiles de <em>wrangling</em>.</p>
<div id="primeros-pasos-al-examinar-un-conjunto-de-datos-nuevo" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Primeros pasos al examinar un conjunto de datos nuevo</h2>
<p>Si no lo hicimos aún en la sesión en la que estamos trabajando, cargamos <code>tidyverse</code>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="poniendo-los-datos-en-forma.html#cb53-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<p>Vamos a practicar usando los registros del Sistema Único de Atención Ciudadana (SUACI) de la Ciudad Autónoma de Buenos Aires. El SUACI es el repositorio donde se integran las solicitudes y reclamos que los ciudadanos presentan a la ciudad por distintos canales: en persona, por teléfono o usando la aplicación <a href="https://gestioncolaborativa.buenosaires.gob.ar/prestaciones">BA 147</a>. Vamos a trabajar con una versión de los datos que ha sido simplificada para hacer más ameno el trabajo con ella. Quién quiera acceder a los datos en su esplendor de complejidad original, puede encontrarlos en el portal de datos abiertos de la ciudad: <a href="https://data.buenosaires.gob.ar/" class="uri">https://data.buenosaires.gob.ar/</a></p>
<p>Comenzamos por acceder al archivo con los registros para cargarlo en R como un dataframe. Tendremos que ejercitar un poco la paciencia porque es un archivo de varios megas, que podría tardar unos minutos en ser descargado.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="poniendo-los-datos-en-forma.html#cb54-1"></a>atencion_ciudadano &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://bitsandbricks.github.io/data/gcba_suaci_barrios.csv&quot;</span>)</span></code></pre></div>
<p>Lo primero que deberíamos hacer con un dataframe que no conocemos es usar la función <code>str()</code>, que nos indica su estructura (por <em>structure</em> en inglés):</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="poniendo-los-datos-en-forma.html#cb55-1"></a><span class="kw">str</span>(atencion_ciudadano)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    57431 obs. of  5 variables:
##  $ PERIODO        : int  201301 201301 201301 201301 201301 201301 201301 201301 201301 201301 ...
##  $ RUBRO          : chr  &quot;ACERAS&quot; &quot;ACERAS&quot; &quot;ACERAS&quot; &quot;ACERAS&quot; ...
##  $ TIPO_PRESTACION: chr  &quot;RECLAMO&quot; &quot;RECLAMO&quot; &quot;RECLAMO&quot; &quot;RECLAMO&quot; ...
##  $ BARRIO         : chr  &quot;AGRONOMIA&quot; &quot;ALMAGRO&quot; &quot;BALVANERA&quot; &quot;BARRACAS&quot; ...
##  $ total          : int  6 172 92 45 79 10 38 109 20 45 ...</code></pre>
<p>Para empezar, nos enteramos que el objeto que estamos analizando es un dataframe (“data.frame”). Eso ya lo sabíamos, pero como <code>str()</code> puede usarse con cualquier clase de objeto en R, en ocasiones resultará que estamos ante un vector, una lista u otra clase de criatura. A continuación aparecen las dimensiones del dataframe: 57.432 observaciones (filas) con 5 variables (columnas). Los nombres de las columnas son PERIODO, RUBRO, TIPO_PRESTACION, BARRIO y total. Con eso ya podemos inferir que cada observación en el dataframe contiene la cantidad total de solicitudes según concepto, rubro y tipo de prestación (aunque no sepamos bien de que se tratan esas variables), en un período dado y en cada barrio.</p>
<p>Con <code>str()</code> también obtenemos el tipo de datos representados pro cada variable, y un ejemplo de los valores contenidos en las primeras filas. <em>PERIODO</em> y <em>total</em> son variables de tipo “int”, es decir, números enteros o <em>integers</em> en inglés. El resto de las variables son de tipo “chr”; en R las variables de texto reciben el nombre de <em>characters</em>, caracteres.</p>
<p>La siguiente función a utilizar cuando estamos conociendo el contenido de un set de datos es <code>summary()</code>, que nos dará un resumen en forma de estadísticas descriptivas para las variables numéricas (cuartiles y mediana) .</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="poniendo-los-datos-en-forma.html#cb57-1"></a><span class="kw">summary</span>(atencion_ciudadano)</span></code></pre></div>
<pre><code>##     PERIODO          RUBRO           TIPO_PRESTACION       BARRIO         
##  Min.   :201301   Length:57431       Length:57431       Length:57431      
##  1st Qu.:201309   Class :character   Class :character   Class :character  
##  Median :201404   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :201401                                                           
##  3rd Qu.:201503                                                           
##  Max.   :201512                                                           
##      total         
##  Min.   :    1.00  
##  1st Qu.:    1.00  
##  Median :    4.00  
##  Mean   :   34.85  
##  3rd Qu.:   16.00  
##  Max.   :19221.00</code></pre>
<p>Para las variables de texto <code>summary()</code> no tiene mucho que decir. Aquí sería bueno que nos mostrara algún dato, quizás los valores más frecuentes, ¿verdad?. Eso va a ocurrir pero sólo cuando esas columnas con texto contengan variables categóricas, que en R reciben el tipo “factor” en lugar de “chr”.</p>
<div class="tip">
<p>Una variable es categórica cuando es razonable considerar que se elige entre un conjunto finito de variables posibles; por ejemplo, los barrios de Buenos Aires son un conjunto finito y predeterminado.</p>
</div>
<p>¿Pero cómo puede saber R si <em>RUBRO</em> o <em>BARRIO</em> son categorías? Pues podemos avisarle al cargar los datos con la función <code>read.csv()</code> que usamos al principio. Para que <code>read.csv()</code> interprete como variables categóricas a todas las columnas que contienen texto se usa el parámetro <code>stringsAsFactors</code>, así: <code>misdatos &lt;- read.csv("archivo_con_mis_datos", stringsAsFactors = TRUE)</code>. En general es buena idea evitar que los campos de texto se asuman como factores, pero en éste caso está bien: aquí todas las columnas de texto, en efecto, contienen variables categóricas.</p>
<p>Veamos que pasa si lo intentamos. Volvemos a leer el mismo dataset, esta vez con <code>stringsAsFactors = TRUE</code></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="poniendo-los-datos-en-forma.html#cb59-1"></a>atencion_ciudadano &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://bitsandbricks.github.io/data/gcba_suaci_barrios.csv&quot;</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p>.. y pedimos su resumen:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="poniendo-los-datos-en-forma.html#cb60-1"></a><span class="kw">summary</span>(atencion_ciudadano)</span></code></pre></div>
<pre><code>##     PERIODO                         RUBRO        TIPO_PRESTACION 
##  Min.   :201301   SANEAMIENTO URBANO   : 4589   DENUNCIA :21606  
##  1st Qu.:201309   TRANSPORTE Y TRANSITO: 4580   QUEJA    : 3914  
##  Median :201404   ARBOLADO             : 3122   RECLAMO  :21038  
##  Mean   :201401   ALUMBRADO            : 2918   SOLICITUD: 9662  
##  3rd Qu.:201503   PAVIMENTO            : 2411   TRAMITE  : 1211  
##  Max.   :201512   ESPACIO PUBLICO      : 1918                    
##                   (Other)              :37893                    
##          BARRIO          total         
##  PALERMO    : 2154   Min.   :    1.00  
##  BALVANERA  : 1961   1st Qu.:    1.00  
##  FLORES     : 1959   Median :    4.00  
##  CABALLITO  : 1872   Mean   :   34.85  
##  SAN NICOLAS: 1748   3rd Qu.:   16.00  
##  RECOLETA   : 1729   Max.   :19221.00  
##  (Other)    :46008</code></pre>
<p>¡Esta vez obtuvimos un ranking con las categorías más frecuentes!</p>
<p>Las categorías posibles para un factor son llamadas “niveles” (<em>levels</em>). Para ver todos los niveles del factor BARRIO, es decir todos los barrios representados en la columna con la variable BARRIO, podemos usar la función <code>levels()</code></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="poniendo-los-datos-en-forma.html#cb62-1"></a><span class="kw">levels</span>(atencion_ciudadano<span class="op">$</span>BARRIO)</span></code></pre></div>
<pre><code>##  [1] &quot; &quot;                    &quot;AGRONOMIA&quot;            &quot;ALMAGRO&quot;             
##  [4] &quot;BALVANERA&quot;            &quot;BARRACAS&quot;             &quot;BELGRANO&quot;            
##  [7] &quot;BOCA&quot;                 &quot;BOEDO&quot;                &quot;CABALLITO&quot;           
## [10] &quot;CHACARITA&quot;            &quot;COGHLAN&quot;              &quot;COLEGIALES&quot;          
## [13] &quot;CONSTITUCION&quot;         &quot;ERRORNOHAYRESULTA&quot;    &quot;ERRORNOHAYRESULTADOS&quot;
## [16] &quot;FLORES&quot;               &quot;FLORESTA&quot;             &quot;LINIERS&quot;             
## [19] &quot;MATADEROS&quot;            &quot;MONSERRAT&quot;            &quot;MONTE CASTRO&quot;        
## [22] &quot;NUEVA POMPEYA&quot;        &quot;NUÑEZ&quot;                &quot;PALERMO&quot;             
## [25] &quot;PARQUE AVELLANEDA&quot;    &quot;PARQUE CHACABUCO&quot;     &quot;PARQUE CHAS&quot;         
## [28] &quot;PARQUE PATRICIOS&quot;     &quot;PATERNAL&quot;             &quot;PUERTO MADERO&quot;       
## [31] &quot;RECOLETA&quot;             &quot;RETIRO&quot;               &quot;SAAVEDRA&quot;            
## [34] &quot;SAN CRISTOBAL&quot;        &quot;SAN NICOLAS&quot;          &quot;SAN TELMO&quot;           
## [37] &quot;VELEZ SARSFIELD&quot;      &quot;VERSALLES&quot;            &quot;VILLA CRESPO&quot;        
## [40] &quot;VILLA DEL PARQUE&quot;     &quot;VILLA DEVOTO&quot;         &quot;VILLA GRAL. MITRE&quot;   
## [43] &quot;VILLA LUGANO&quot;         &quot;VILLA LURO&quot;           &quot;VILLA ORTUZAR&quot;       
## [46] &quot;VILLA PUEYRREDON&quot;     &quot;VILLA REAL&quot;           &quot;VILLA RIACHUELO&quot;     
## [49] &quot;VILLA SANTA RITA&quot;     &quot;VILLA SOLDATI&quot;        &quot;VILLA URQUIZA&quot;</code></pre>
<p>Para acceder en forma rápida al contenido de la columna BARRIO, hemos utilizado por primera vez un “truco” muy práctico. Para obtener el contenido de cualquier columna en particular, basta con el nombre del dataframe seguido del símbolo <code>$</code> y el nombre de la columna a extraer: <code>atencion_ciudadano$BARRIO</code>, o <code>atencion_ciudadano$total</code>, etc.</p>
</div>
<div id="cruzando-variables-la-operación-join" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Cruzando variables: la operación <code>join</code></h2>
<p>Al realizar un análisis “en la vida real”, es decir, usando datos salvajes en lugar de los prolijos datasets de práctica, es muy habitual encontrar que nos falta una variable que necesitamos. Si tenemos suerte, la información que necesitamos también está disponible en forma de tabla, con algún campo en común, y podemos llevar el cabo un cruce de datos para traérnosla.</p>
<p>Para expresarlo con un ejemplo concreto: hemos visto que los registros de atención al ciudadano incluyen una columna con el barrio, que es la única variable relacionada con la geografía. Si nuestra unidad de análisis fuera la columna en lugar del barrio, necesitaríamos agrega la columna correspondiente. En este caso, estamos de suerte porque una tabla con los barrios de la Ciudad de Buenos Aires y la comuna a la que pertenecen es fácil de conseguir. Con esa tabla en nuestro poder, ya tenemos las piezas necesarias para el cruce de datos. En cada registro en el dataframe de atención al ciudadano, tenemos un barrio; podemos buscarlo en la tabla de barrios y comunas, tomar nota de la comuna asociada, y copiarla en nuestro dataset original. Por supuesto, hacerlo a mano para cada uno de las 57.432 filas en nuestro dataframe tardaría una eternidad, amén de que quizás perderíamos la cordura antes de terminar. ¡Nada de eso! Vamos a resolverlo en meros instantes escribiendo unas pocas líneas de código. Antes de continuar hagamos una pausa para conmiserar a los investigadores de eras pasadas, antes de la popularización de la computadora personal, que realizaban tareas de esta escala con lápiz, papel y paciencia.</p>
<p>Existe una gran variedad de funciones que permiten combinar tablas relacionadas entre sí por una o varias variables en común. Para nuestro propósito, alcanza con conocer una: <code>left_join()</code>. La función toma como parámetros dos dataframes (que son tablas al fin y al cabo) busca las variables que tengan el mismo nombre y usándolas como referencia completa la primera de ellas, la de la izquierda, con los datos nuevos que aporta la segunda. <code>left_join</code> devuelve un dataframe nuevo con los datos combinados.</p>
<p>Manos a la obra. Descargamos el dataframe con barrios y comunas,</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="poniendo-los-datos-en-forma.html#cb64-1"></a>barrios_comunas &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://bitsandbricks.github.io/data/barrios_comunas.csv&quot;</span>)</span></code></pre></div>
<p>echamos un vistazo, comprobando que existe BARRIOS, una columna en común que lo relaciona con el dataframe de atención al ciudadano,</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="poniendo-los-datos-en-forma.html#cb65-1"></a>barrios_comunas</span></code></pre></div>
<pre><code>##               BARRIO COMUNA
## 1          AGRONOMIA     15
## 2            ALMAGRO      5
## 3          BALVANERA      3
## 4           BARRACAS      4
## 5           BELGRANO     13
## 6               BOCA      4
## 7              BOEDO      5
## 8          CABALLITO      6
## 9          CHACARITA     15
## 10           COGHLAN     12
## 11        COLEGIALES     13
## 12      CONSTITUCION      1
## 13            FLORES      7
## 14          FLORESTA     10
## 15           LINIERS      9
## 16         MATADEROS      9
## 17         MONSERRAT      1
## 18      MONTE CASTRO     10
## 19     NUEVA POMPEYA      4
## 20             NUÑEZ     13
## 21           PALERMO     14
## 22 PARQUE AVELLANEDA      9
## 23  PARQUE CHACABUCO      7
## 24       PARQUE CHAS     15
## 25  PARQUE PATRICIOS      4
## 26          PATERNAL     15
## 27     PUERTO MADERO      1
## 28          RECOLETA      2
## 29            RETIRO      1
## 30          SAAVEDRA     12
## 31     SAN CRISTOBAL      3
## 32       SAN NICOLAS      1
## 33         SAN TELMO      1
## 34   VELEZ SARSFIELD     10
## 35         VERSALLES     10
## 36      VILLA CRESPO     15
## 37  VILLA DEL PARQUE     11
## 38      VILLA DEVOTO     11
## 39 VILLA GRAL. MITRE     11
## 40      VILLA LUGANO      8
## 41        VILLA LURO     10
## 42     VILLA ORTUZAR     15
## 43  VILLA PUEYRREDON     12
## 44        VILLA REAL     10
## 45   VILLA RIACHUELO      8
## 46  VILLA SANTA RITA     11
## 47     VILLA SOLDATI      8
## 48     VILLA URQUIZA     12</code></pre>
<p>y lo unimos (de allí el término “join”, unir en inglés) a nuestra data:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="poniendo-los-datos-en-forma.html#cb67-1"></a>atencion_ciudadano &lt;-<span class="st"> </span><span class="kw">left_join</span>(atencion_ciudadano, barrios_comunas)</span></code></pre></div>
<pre><code>## Joining, by = &quot;BARRIO&quot;</code></pre>
<p>Admiremos nuestra obra:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="poniendo-los-datos-en-forma.html#cb69-1"></a><span class="kw">head</span>(atencion_ciudadano)</span></code></pre></div>
<pre><code>##   PERIODO  RUBRO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201301 ACERAS         RECLAMO AGRONOMIA     6     15
## 2  201301 ACERAS         RECLAMO   ALMAGRO   172      5
## 3  201301 ACERAS         RECLAMO BALVANERA    92      3
## 4  201301 ACERAS         RECLAMO  BARRACAS    45      4
## 5  201301 ACERAS         RECLAMO  BELGRANO    79     13
## 6  201301 ACERAS         RECLAMO      BOCA    10      4</code></pre>
<p>Es así de fácil. Bueno, no tanto… este fue un caso sencillo, pero hay todo tipo de datos y cruces allí afuera, y a veces se necesitan operaciones más complejas. Por eso hay toda una familia de funciones de <em>join</em> - <code>right_join()</code>, <code>inner_join()</code>, <code>full_join</code>, <code>anti_join()</code>, y alguna más. Pero podemos dejarlas en paz; para nuestras necesidades, con <code>left_join()</code> podemos alegrarnos muy bien.</p>
<p>Satisfechos con la mejora, si queremos guardar el dataframe “mejorado” para usarlo en otra ocasión, podemos hacerlo con <code>write.csv()</code>, que lo convierte en un archivo de texto que queda en nuestra PC.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="poniendo-los-datos-en-forma.html#cb71-1"></a><span class="kw">write.csv</span>(atencion_ciudadano, <span class="st">&quot;atencion_ciudadano.csv&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<p>Podemos seguir siempre ese formato para guardar nuestros datos. El primer parámetro es el dataframe que vamos a guardar, el segundo -siempre entre comillas- es el nombre de archivo, y la opción final, <code>row.names = FALSE</code> sirve para evitar que R le agregue una columna al principio con números consecutivos (1, 2, 3, y así), cosa que quizás fue útil alguna vez pero en general no necesitamos.</p>
<p>Para volver a leer los datos en otra ocasión, usamos <code>read.csv()</code> tal como ya hemos hecho.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="poniendo-los-datos-en-forma.html#cb72-1"></a>atencion_ciudadano &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;atencion_ciudadano.csv&quot;</span>)</span></code></pre></div>
<p>Y si queremos saber exactamente dónde ha guardado R nuestros datos, por ejemplo para abrirlos con otro programa, usamos la función <code>getwd</code> (por <em>get working directory</em> )</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="poniendo-los-datos-en-forma.html#cb73-1"></a><span class="kw">getwd</span>()</span></code></pre></div>
<pre><code>## [1] &quot;/home/havb/Documents/repos/CD_AJ&quot;</code></pre>
<p>El resultado será la dirección (la ubicación de la la carpeta), donde estamos trabajando y hemos guardado los datos; por ejemplo <code>/home/antonio/Practicando R/</code>.</p>
</div>
<div id="transformando-los-datos" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Transformando los datos</h2>
<p>Habiendo revisado el contenido de un dataframe (y agregado alguna variable si hiciera falta), comenzamos a hacernos idea de los ajustes que necesita para que los datos tomen el formato que necesitamos. Estos ajustes pueden ser correcciones (por ejemplo, de errores de tipeo cuando se cargaron los datos), la creación de nuevas variables derivadas de las existentes, o un reordenamiento de los datos para simplificar nuestro trabajo.</p>
<p>Para hacer todo esto, y mucho más, vamos a aprender funciones que representan cinco verbos básicos para la transformación de datos:</p>
<ul>
<li><code>select()</code>: seleccionar -elegir- columnas por su nombre</li>
<li><code>filter()</code>: filtrar, es decir quedarse sólo con las filas que cumplan cierta condición</li>
<li><code>arrange()</code>: ordenar las filas de acuerdo a su contenido o algún otro índice</li>
<li><code>mutate()</code>: mutar -cambiar- un dataframe, modificando el contenido de sus columnas o creando columnas (es decir, variables) nuevas</li>
<li><code>summarise()</code>: producir sumarios -un valor extraído de muchos, por ejemplo el promedio- con el contenido de las columnas</li>
</ul>
<p>Estas funciones tienen una sintaxis, una forma de escribirse, uniforme. El primer argumento que toman siempre es un dataframe; los siguientes indican qué hacer con los datos. El resultado siempre es un nuevo dataframe.</p>
<p>Las funciones son parte de <a href="http://dplyr.tidyverse.org/">dplyr</a>, uno de los componentes de la familia de paquetes <a href="https://www.tidyverse.org/">Tidyverse</a>. Ya tenemos disponible todo lo necesario, activado cuando invocamos <code>library(tidyverse)</code> al comienzo.</p>
<p>Manos a la obra.</p>
<div id="seleccionar-columnas-con-select" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Seleccionar columnas con <code>select()</code></h3>
<p>Muchas veces tendremos que lidiar con datasets con decenas de variables. Alguna que otra vez, con centenas. En esos casos el primer problema es librarnos de semejante cantidad de columnas, reteniendo sólo aquellas en las que estamos interesados. Para un dataset como el de reclamos de los ciudadanos, que tiene pocas columnas, select() no es tan importante. Aún así, podemos usar select() con fines demostrativos.</p>
<p>Sabemos que el dataset tiene 5 columnas:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="poniendo-los-datos-en-forma.html#cb75-1"></a><span class="kw">names</span>(atencion_ciudadano)</span></code></pre></div>
<pre><code>## [1] &quot;PERIODO&quot;         &quot;RUBRO&quot;           &quot;TIPO_PRESTACION&quot; &quot;BARRIO&quot;         
## [5] &quot;total&quot;           &quot;COMUNA&quot;</code></pre>
<p>Si quisiéramos sólo las que contienen el período y el total, las seleccionamos por nombre, a continuación del nombre del dataframe:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="poniendo-los-datos-en-forma.html#cb77-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">select</span>(atencion_ciudadano, PERIODO, total)</span>
<span id="cb77-2"><a href="poniendo-los-datos-en-forma.html#cb77-2"></a></span>
<span id="cb77-3"><a href="poniendo-los-datos-en-forma.html#cb77-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO total
## 1  201301     6
## 2  201301   172
## 3  201301    92
## 4  201301    45
## 5  201301    79
## 6  201301    10</code></pre>
<p>También podemos seleccionar por contigüidad, por ejemplo “todas las columnas que van de RUBRO a BARRIO”:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="poniendo-los-datos-en-forma.html#cb79-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">select</span>(atencion_ciudadano, RUBRO<span class="op">:</span>BARRIO)</span>
<span id="cb79-2"><a href="poniendo-los-datos-en-forma.html#cb79-2"></a></span>
<span id="cb79-3"><a href="poniendo-los-datos-en-forma.html#cb79-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##    RUBRO TIPO_PRESTACION    BARRIO
## 1 ACERAS         RECLAMO AGRONOMIA
## 2 ACERAS         RECLAMO   ALMAGRO
## 3 ACERAS         RECLAMO BALVANERA
## 4 ACERAS         RECLAMO  BARRACAS
## 5 ACERAS         RECLAMO  BELGRANO
## 6 ACERAS         RECLAMO      BOCA</code></pre>
<p>Y podemos seleccionar por omisión. Si nos interesara todo el contenido del dataset menos la variable RUBRO, usaríamos</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="poniendo-los-datos-en-forma.html#cb81-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">select</span>(atencion_ciudadano, <span class="op">-</span>RUBRO)</span>
<span id="cb81-2"><a href="poniendo-los-datos-en-forma.html#cb81-2"></a></span>
<span id="cb81-3"><a href="poniendo-los-datos-en-forma.html#cb81-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201301         RECLAMO AGRONOMIA     6     15
## 2  201301         RECLAMO   ALMAGRO   172      5
## 3  201301         RECLAMO BALVANERA    92      3
## 4  201301         RECLAMO  BARRACAS    45      4
## 5  201301         RECLAMO  BELGRANO    79     13
## 6  201301         RECLAMO      BOCA    10      4</code></pre>
<p>Al igual que con las selección por inclusión, podemos seleccionar por omisión de un rango de columnas contiguas (escritas entre paréntesis), o de varias columnas nombradas:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="poniendo-los-datos-en-forma.html#cb83-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">select</span>(atencion_ciudadano, <span class="op">-</span>(TIPO_PRESTACION<span class="op">:</span>total))</span>
<span id="cb83-2"><a href="poniendo-los-datos-en-forma.html#cb83-2"></a></span>
<span id="cb83-3"><a href="poniendo-los-datos-en-forma.html#cb83-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO  RUBRO COMUNA
## 1  201301 ACERAS     15
## 2  201301 ACERAS      5
## 3  201301 ACERAS      3
## 4  201301 ACERAS      4
## 5  201301 ACERAS     13
## 6  201301 ACERAS      4</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="poniendo-los-datos-en-forma.html#cb85-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">select</span>(atencion_ciudadano, <span class="op">-</span>RUBRO, <span class="op">-</span>BARRIO)</span>
<span id="cb85-2"><a href="poniendo-los-datos-en-forma.html#cb85-2"></a></span>
<span id="cb85-3"><a href="poniendo-los-datos-en-forma.html#cb85-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO TIPO_PRESTACION total COMUNA
## 1  201301         RECLAMO     6     15
## 2  201301         RECLAMO   172      5
## 3  201301         RECLAMO    92      3
## 4  201301         RECLAMO    45      4
## 5  201301         RECLAMO    79     13
## 6  201301         RECLAMO    10      4</code></pre>
</div>
<div id="filtrar-filas-con-filter" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Filtrar filas con <code>filter()</code></h3>
<p>Una de las tareas más frecuentes en el análisis de datos es la de identificar observaciones que cumplen con determinada condición. <code>filter()</code> permite extraer subconjuntos del total en base a sus variables.</p>
<p>Por ejemplo, para seleccionar registros que correspondan a Retiro, ocurridos en el primer mes de 2014 (período 201401):</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="poniendo-los-datos-en-forma.html#cb87-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, BARRIO <span class="op">==</span><span class="st"> &quot;RETIRO&quot;</span>, PERIODO <span class="op">==</span><span class="st"> </span><span class="dv">201401</span>)</span>
<span id="cb87-2"><a href="poniendo-los-datos-en-forma.html#cb87-2"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO               RUBRO TIPO_PRESTACION BARRIO total COMUNA
## 1  201401              ACERAS         RECLAMO RETIRO    10      1
## 2  201401           ALUMBRADO         RECLAMO RETIRO    34      1
## 3  201401           ALUMBRADO       SOLICITUD RETIRO     2      1
## 4  201401            ARBOLADO         RECLAMO RETIRO    10      1
## 5  201401            ARBOLADO       SOLICITUD RETIRO     3      1
## 6  201401 ATENCION AL PUBLICO           QUEJA RETIRO     3      1</code></pre>
<div id="comparaciones" class="section level4" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> Comparaciones</h4>
<p>Aquí hemos usado un recurso nuevo, la comparación. R provee una serie de símbolos que permite comparar valores entre sí:</p>
<pre><code>* ==   igual a 
* !=   no igual a 
* &gt;    mayor a 
* &gt;=   mayor o igual a 
* &lt;    menor a 
* &lt;=   menor o igual a </code></pre>
<p>Atención especial merece el símbolo que compara igualdad, <code>==</code>. Un error muy común es escribir <code>BARRIO = "RETIRO"</code>, (un sólo símbolo <code>=</code>) que le indica a R que guarde el valor “RETIRO” dentro de la variable BARRIO, en lugar de verificar si son iguales. Para ésto último, lo correcto es <code>BARRIO == "RETIRO"</code>, tal como lo usamos en el ejemplo de filter().</p>
<p>También hay que tener en cuenta el uso de comillas. Para que R no se confunda, cuando queramos usar valores de texto (de tipo <em>character</em>) los rodeamos con comillas para que quede claro que no nos referimos a una variable con ese nombre, si la hubiera, sino en forma literal a esa palabra o secuencia de texto. En el caso de los números, no hace falta el uso de comillas, ya que en R ningún nombre de variable puede comenzar con o estar compuesta sólo por números.</p>
<p>Filtrando los registros de períodos para los cuales se registran más de 100 incidentes:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="poniendo-los-datos-en-forma.html#cb90-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, total <span class="op">&gt;</span><span class="st"> </span><span class="dv">100</span>)</span>
<span id="cb90-2"><a href="poniendo-los-datos-en-forma.html#cb90-2"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO     RUBRO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201301    ACERAS         RECLAMO   ALMAGRO   172      5
## 2  201301    ACERAS         RECLAMO CABALLITO   109      6
## 3  201301    ACERAS         RECLAMO    FLORES   111      7
## 4  201301    ACERAS         RECLAMO   PALERMO   113     14
## 5  201301 ALUMBRADO         RECLAMO   ALMAGRO   130      5
## 6  201301 ALUMBRADO         RECLAMO  BARRACAS   118      4</code></pre>
</div>
<div id="operadores-lógicos" class="section level4" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Operadores lógicos</h4>
<p>Cuando le pasamos múltiples condiciones a filter(), la función devuelve las filas que cumplen con todas.</p>
<p>Por ejemplo, con</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="poniendo-los-datos-en-forma.html#cb92-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, PERIODO <span class="op">==</span><span class="st"> </span><span class="dv">201508</span>,  RUBRO <span class="op">==</span><span class="st"> &quot;SALUD&quot;</span>)</span>
<span id="cb92-2"><a href="poniendo-los-datos-en-forma.html#cb92-2"></a></span>
<span id="cb92-3"><a href="poniendo-los-datos-en-forma.html#cb92-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO RUBRO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201508 SALUD           QUEJA  BARRACAS     1      4
## 2  201508 SALUD           QUEJA CABALLITO     1      6
## 3  201508 SALUD           QUEJA   COGHLAN     1     12
## 4  201508 SALUD           QUEJA  RECOLETA     1      2</code></pre>
<p>obtenemos todos los registros cuyo rubro es “SALUD”, y cuyo período es 20108, agosto de 2015.</p>
<p>Siguiendo el mismo formato, si intentamos</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="poniendo-los-datos-en-forma.html#cb94-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, BARRIO <span class="op">==</span><span class="st"> &quot;RETIRO&quot;</span>, BARRIO <span class="op">==</span><span class="st"> &quot;PALERMO&quot;</span>)</span>
<span id="cb94-2"><a href="poniendo-los-datos-en-forma.html#cb94-2"></a></span>
<span id="cb94-3"><a href="poniendo-los-datos-en-forma.html#cb94-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>## [1] PERIODO         RUBRO           TIPO_PRESTACION BARRIO         
## [5] total           COMUNA         
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<p>obtenemos un conjunto vacío. ¿Por qué? Es debido a que ninguna observación cumple con todas las condiciones; el ningún registro el barrio es Retiro y es Palermo. ¡Suena razonable!. Para obtener registros ocurrido en Retiro <strong>ó</strong> en Palermo, usamos el operador lógico <code>|</code> que significa… “ó”.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="poniendo-los-datos-en-forma.html#cb96-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, BARRIO <span class="op">==</span><span class="st"> &quot;RETIRO&quot;</span> <span class="op">|</span><span class="st"> </span>BARRIO <span class="op">==</span><span class="st"> &quot;PALERMO&quot;</span>)</span>
<span id="cb96-2"><a href="poniendo-los-datos-en-forma.html#cb96-2"></a></span>
<span id="cb96-3"><a href="poniendo-los-datos-en-forma.html#cb96-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO               RUBRO TIPO_PRESTACION  BARRIO total COMUNA
## 1  201301              ACERAS         RECLAMO PALERMO   113     14
## 2  201301              ACERAS         RECLAMO  RETIRO    15      1
## 3  201301              ACERAS       SOLICITUD PALERMO     2     14
## 4  201301 ACTOS DE CORRUPCION        DENUNCIA PALERMO     4     14
## 5  201301           ALUMBRADO         RECLAMO PALERMO    74     14
## 6  201301           ALUMBRADO         RECLAMO  RETIRO    15      1</code></pre>
<p>Se trata de la lógica de conjuntos, o lógica <em>booleana</em>, que con un poco de suerte recordamos de nuestra época de escolares. Los símbolos importantes son <code>&amp;</code>, <code>|</code>, y <code>!</code>: “y”, “ó”, y la negación que invierte preposiciones:</p>
<pre><code>* a &amp; b     a y b
* a | b     a ó b
* a &amp; !b    a, y no b
* !a &amp; b    no a, y b
* !(a &amp; b)  no (a y b) </code></pre>
<p>Hemos visto ejemplos de <code>a &amp; b</code> (<code>PERIODO == 201508,  RUBRO == "SALUD"</code>, que filter toma como un <code>&amp;</code>) y de <code>a | b</code> (<code>BARRIO == "RETIRO" | BARRIO == "PALERMO"</code>)</p>
<p>Un ejemplo de <code>a &amp; !b</code>, filas en las que el tipo de prestación sea “TRAMITE”, y en las que el rubro no sea “REGISTRO CIVIL”:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="poniendo-los-datos-en-forma.html#cb99-1"></a><span class="kw">filter</span>(atencion_ciudadano, TIPO_PRESTACION <span class="op">==</span><span class="st"> &quot;TRAMITE&quot;</span> <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span>(RUBRO <span class="op">==</span><span class="st"> &quot;REGISTRO CIVIL&quot;</span>))</span></code></pre></div>
<p>Y como ejemplo de <code>!(a &amp; b)</code>, todas las filas excepto las de tipo “DENUNCIA”, y rubro “SEGURIDAD E HIGIENE”:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="poniendo-los-datos-en-forma.html#cb100-1"></a>seleccion &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, <span class="op">!</span>(TIPO_PRESTACION <span class="op">==</span><span class="st"> &quot;DENUNCIA&quot;</span> <span class="op">&amp;</span><span class="st"> </span>RUBRO <span class="op">==</span><span class="st"> &quot;SEGURIDAD E HIGIENE&quot;</span>))</span>
<span id="cb100-2"><a href="poniendo-los-datos-en-forma.html#cb100-2"></a></span>
<span id="cb100-3"><a href="poniendo-los-datos-en-forma.html#cb100-3"></a><span class="kw">head</span>(seleccion)</span></code></pre></div>
<pre><code>##   PERIODO  RUBRO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201301 ACERAS         RECLAMO AGRONOMIA     6     15
## 2  201301 ACERAS         RECLAMO   ALMAGRO   172      5
## 3  201301 ACERAS         RECLAMO BALVANERA    92      3
## 4  201301 ACERAS         RECLAMO  BARRACAS    45      4
## 5  201301 ACERAS         RECLAMO  BELGRANO    79     13
## 6  201301 ACERAS         RECLAMO      BOCA    10      4</code></pre>
</div>
</div>
<div id="ordenar-filas-con-arrange" class="section level3" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Ordenar filas con <code>arrange()</code></h3>
<p>La función <code>arrange()</code> cambia el orden en el que aparecen las filas de un dataframe. Como primer parámetro toma un dataframe, al igual que el resto de los verbos de transformación que estamos aprendiendo. A continuación, espera un set de columnas para definir el orden.</p>
<p>Por ejemplo, para ordenar por total de registros:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="poniendo-los-datos-en-forma.html#cb102-1"></a>ordenado &lt;-<span class="st"> </span><span class="kw">arrange</span>(atencion_ciudadano, total)</span>
<span id="cb102-2"><a href="poniendo-los-datos-en-forma.html#cb102-2"></a></span>
<span id="cb102-3"><a href="poniendo-los-datos-en-forma.html#cb102-3"></a><span class="kw">head</span>(ordenado)</span></code></pre></div>
<pre><code>##   PERIODO  RUBRO TIPO_PRESTACION        BARRIO total COMUNA
## 1  201301 ACERAS         RECLAMO PUERTO MADERO     1      1
## 2  201301 ACERAS       SOLICITUD      BARRACAS     1      4
## 3  201301 ACERAS       SOLICITUD          BOCA     1      4
## 4  201301 ACERAS       SOLICITUD         BOEDO     1      5
## 5  201301 ACERAS       SOLICITUD       COGHLAN     1     12
## 6  201301 ACERAS       SOLICITUD  CONSTITUCION     1      1</code></pre>
<p>Si agregamos más columnas, se usan en orden para “desempatar”. Por ejemplo, si queremos que las filas con el mismo valor en <em>total</em> aparezcan en el orden alfabético del barrio que les corresponde, sólo necesitamos agregar esa columna:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="poniendo-los-datos-en-forma.html#cb104-1"></a>ordenado &lt;-<span class="st"> </span><span class="kw">arrange</span>(atencion_ciudadano, total, BARRIO)</span>
<span id="cb104-2"><a href="poniendo-los-datos-en-forma.html#cb104-2"></a></span>
<span id="cb104-3"><a href="poniendo-los-datos-en-forma.html#cb104-3"></a><span class="kw">head</span>(ordenado)</span></code></pre></div>
<pre><code>##   PERIODO           RUBRO TIPO_PRESTACION    BARRIO total COMUNA
## 1  201301       ALUMBRADO       SOLICITUD AGRONOMIA     1     15
## 2  201301 ATENCION SOCIAL         RECLAMO AGRONOMIA     1     15
## 3  201301 ESPACIO PUBLICO         RECLAMO AGRONOMIA     1     15
## 4  201301           QUEJA           QUEJA AGRONOMIA     1     15
## 5  201301   RECUPERADORES         RECLAMO AGRONOMIA     1     15
## 6  201301       SEGURIDAD         RECLAMO AGRONOMIA     1     15</code></pre>
<p>Si no se aclara lo contrario, el orden siempre es ascendente (de menor a mayor). Si quisiéramos orden de mayor a menor, usamos <code>desc()</code>:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="poniendo-los-datos-en-forma.html#cb106-1"></a>ordenado &lt;-<span class="st"> </span><span class="kw">arrange</span>(atencion_ciudadano, <span class="kw">desc</span>(total))</span>
<span id="cb106-2"><a href="poniendo-los-datos-en-forma.html#cb106-2"></a></span>
<span id="cb106-3"><a href="poniendo-los-datos-en-forma.html#cb106-3"></a><span class="kw">head</span>(ordenado)</span></code></pre></div>
<pre><code>##   PERIODO          RUBRO TIPO_PRESTACION      BARRIO total COMUNA
## 1  201502 REGISTRO CIVIL         TRAMITE   MONSERRAT 19221      1
## 2  201403 REGISTRO CIVIL         TRAMITE SAN NICOLAS 19209      1
## 3  201402 REGISTRO CIVIL         TRAMITE SAN NICOLAS 17032      1
## 4  201504 REGISTRO CIVIL         TRAMITE   MONSERRAT 16746      1
## 5  201503 REGISTRO CIVIL         TRAMITE   MONSERRAT 16730      1
## 6  201506 REGISTRO CIVIL         TRAMITE   MONSERRAT 14674      1</code></pre>
<div id="valores-faltantes" class="section level4" number="3.3.3.1">
<h4><span class="header-section-number">3.3.3.1</span> Valores faltantes</h4>
<p>En el último ejemplo, aparecen varias filas cuyo valor para la columna BARRIO es <code>NA</code>. R representa los valores ausentes, desconocidos, con <code>NA</code> (“no disponible”, del inglés <em>Not Available</em>). Hay que tener cuidado con los valores <code>NA</code>, porque la mayoría de las comparaciones y operaciones lógicas que los involucran resultan indefinidas. En la práctica:</p>
<p>¿Es 10 mayor a un valor desconocido?</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="poniendo-los-datos-en-forma.html#cb108-1"></a><span class="dv">10</span> <span class="op">&gt;</span><span class="st"> </span><span class="ot">NA</span></span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>R no sabe. (Nadie lo sabe, para ser justos)</p>
<p>¿A cuanto asciende la suma de 10 más un valor desconocido?</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="poniendo-los-datos-en-forma.html#cb110-1"></a><span class="ot">NA</span> <span class="op">+</span><span class="st"> </span><span class="dv">10</span></span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Y en particular… ¿es un valor desconocido igual a otro valor desconocido?</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="poniendo-los-datos-en-forma.html#cb112-1"></a><span class="ot">NA</span> <span class="op">==</span><span class="st"> </span><span class="ot">NA</span></span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Por supuesto, la respuesta es desconocida también. La insistencia de R en no definir operaciones que involucran NA’s podría parecer irritante a primera vista, pero en realidad nos hace un favor. Al evitar extraer conclusiones cuando trata con datos faltantes, nos evita caer en errores garrafales en los casos en que analizamos y comparamos datos incompletos. Además, podemos preguntar a R si un valor es desconocido, y allí si contesta con seguridad. La función requerida es <code>is.na()</code>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="poniendo-los-datos-en-forma.html#cb114-1"></a>desconocido &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb114-2"><a href="poniendo-los-datos-en-forma.html#cb114-2"></a></span>
<span id="cb114-3"><a href="poniendo-los-datos-en-forma.html#cb114-3"></a><span class="kw">is.na</span>(desconocido)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Algo más a tener en cuenta con los valores desconocidos es cómo son interpretados cuando usamos funciones de transformación de datos. Por ejemplo, <code>filter()</code> ignora las filas que contienen NA’s en la variable que usa para filtrar. <code>arrange()</code> muestra las filas con NA’s en el campo por el que ordena, pero todas al final.</p>
</div>
</div>
<div id="agregar-nuevas-variables-con-mutate" class="section level3" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Agregar nuevas variables con <code>mutate()</code></h3>
<p>Recurrimos a la función <code>mutate()</code> cuando queremos agregarle columnas adicionales a nuestro dataframe, en general en base a los valores de las columnas ya existentes. Vamos a ilustrarlo con un ejemplo sencillo. Imaginemos que tenemos el siguiente dataset:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="poniendo-los-datos-en-forma.html#cb116-1"></a>circulos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">nombre =</span> <span class="kw">c</span>(<span class="st">&quot;Círculo 1&quot;</span>, <span class="st">&quot;Círculo 2&quot;</span>, <span class="st">&quot;Círculo 3&quot;</span>),</span>
<span id="cb116-2"><a href="poniendo-los-datos-en-forma.html#cb116-2"></a>                       tamaño =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Pequeño&quot;</span>, <span class="st">&quot;Mediano&quot;</span>, <span class="st">&quot;Grande&quot;</span>),</span>
<span id="cb116-3"><a href="poniendo-los-datos-en-forma.html#cb116-3"></a>                       <span class="dt">radio  =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>))</span>
<span id="cb116-4"><a href="poniendo-los-datos-en-forma.html#cb116-4"></a></span>
<span id="cb116-5"><a href="poniendo-los-datos-en-forma.html#cb116-5"></a>circulos</span></code></pre></div>
<pre><code>##      nombre  tamaño radio
## 1 Círculo 1 Pequeño     1
## 2 Círculo 2 Mediano     3
## 3 Círculo 3  Grande     5</code></pre>
<p>Podemos agregar una columna con el área de cada círculo con mutate():</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="poniendo-los-datos-en-forma.html#cb118-1"></a><span class="kw">mutate</span>(circulos, <span class="dt">area =</span> <span class="fl">3.1416</span> <span class="op">*</span><span class="st"> </span>radio<span class="op">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      nombre  tamaño radio    area
## 1 Círculo 1 Pequeño     1  3.1416
## 2 Círculo 2 Mediano     3 28.2744
## 3 Círculo 3  Grande     5 78.5400</code></pre>
<p>Usando mutate(), definimos la columna “area”, indicando que su contenido será el valor de la columna “radio” en cada registro puesto en la fórmula del área de un círculo. Los operadores aritméticos (<code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, <code>^</code>) son con frecuencia útiles para usar en conjunto con mutate().</p>
<p>Volvamos ahora a nuestro dataframe con datos de reclamos. Supongamos que nos interesa agregar columnas con el mes y el año de cada registro. La columna período, con valores del tipo “201301”, contiene la información necesaria para derivar estas dos nuevas variables. Para separar la parte del año de la parte del mes, la función <code>substr()</code>, que extrae porciones de una variable de texto, nos va a dar una mano. La usamos así: el primer parámetro es una secuencia de caracteres, y los dos siguientes indican donde queremos que empiece y termine la porción a extraer.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="poniendo-los-datos-en-forma.html#cb120-1"></a>atencion_ciudadano &lt;-<span class="st"> </span><span class="kw">mutate</span>(atencion_ciudadano,</span>
<span id="cb120-2"><a href="poniendo-los-datos-en-forma.html#cb120-2"></a>                             AÑO =<span class="st"> </span><span class="kw">substr</span>(PERIODO, <span class="dv">1</span>, <span class="dv">4</span>),</span>
<span id="cb120-3"><a href="poniendo-los-datos-en-forma.html#cb120-3"></a>                             <span class="dt">MES =</span> <span class="kw">substr</span>(PERIODO, <span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb120-4"><a href="poniendo-los-datos-en-forma.html#cb120-4"></a>                                </span>
<span id="cb120-5"><a href="poniendo-los-datos-en-forma.html#cb120-5"></a><span class="kw">head</span>(atencion_ciudadano) </span></code></pre></div>
<pre><code>##   PERIODO  RUBRO TIPO_PRESTACION    BARRIO total COMUNA  AÑO MES
## 1  201301 ACERAS         RECLAMO AGRONOMIA     6     15 2013  01
## 2  201301 ACERAS         RECLAMO   ALMAGRO   172      5 2013  01
## 3  201301 ACERAS         RECLAMO BALVANERA    92      3 2013  01
## 4  201301 ACERAS         RECLAMO  BARRACAS    45      4 2013  01
## 5  201301 ACERAS         RECLAMO  BELGRANO    79     13 2013  01
## 6  201301 ACERAS         RECLAMO      BOCA    10      4 2013  01</code></pre>
</div>
<div id="extraer-sumarios-con-summarise" class="section level3" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Extraer sumarios con <code>summarise()</code></h3>
<p>Llegamos al último de los verbos fundamentales para transformar datos. <code>summarise()</code> (por “resumir” en inglés) toma un dataframe completo y lo resume un una sola fila, de acuerdo a la operación que indiquemos. Por ejemplo, el promedio de la columna “total”:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="poniendo-los-datos-en-forma.html#cb122-1"></a><span class="kw">summarise</span>(atencion_ciudadano, <span class="dt">promedio =</span> <span class="kw">mean</span>(total))</span></code></pre></div>
<pre><code>##   promedio
## 1  34.8478</code></pre>
<p>Por si sola, <code>summarise()</code> no es de mucha ayuda. La gracia está en combinarla con <code>group_by()</code>, que cambia la unidad de análisis del dataframe completo a grupos individuales. Usar <code>summarise()</code> sobre un dataframe al que antes agrupamos con <code>group_by</code> resulta en resúmenes “por grupo”.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="poniendo-los-datos-en-forma.html#cb124-1"></a>agrupado &lt;-<span class="st"> </span><span class="kw">group_by</span>(atencion_ciudadano, AÑO)</span>
<span id="cb124-2"><a href="poniendo-los-datos-en-forma.html#cb124-2"></a></span>
<span id="cb124-3"><a href="poniendo-los-datos-en-forma.html#cb124-3"></a><span class="kw">summarise</span>(agrupado, <span class="dt">promedio_totales =</span> <span class="kw">mean</span>(total))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   AÑO   promedio_totales
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 2013              29.5
## 2 2014              30.2
## 3 2015              45.4</code></pre>
<p>Podemos agrupar por múltiples columnas, generando más subgrupos; por ejemplo, promedios por por año y mes…</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="poniendo-los-datos-en-forma.html#cb126-1"></a>agrupado &lt;-<span class="st"> </span><span class="kw">group_by</span>(atencion_ciudadano, AÑO, MES)</span>
<span id="cb126-2"><a href="poniendo-los-datos-en-forma.html#cb126-2"></a></span>
<span id="cb126-3"><a href="poniendo-los-datos-en-forma.html#cb126-3"></a>sumario &lt;-<span class="st"> </span><span class="kw">summarise</span>(agrupado, <span class="dt">promedio =</span> <span class="kw">mean</span>(total))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;AÑO&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="poniendo-los-datos-en-forma.html#cb128-1"></a><span class="kw">head</span>(sumario)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
## # Groups:   AÑO [1]
##   AÑO   MES   promedio
##   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
## 1 2013  01        25.1
## 2 2013  02        26.1
## 3 2013  03        26.9
## 4 2013  04        29.5
## 5 2013  05        28.0
## 6 2013  06        28.9</code></pre>
<p>… o por año, mes y barrio:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="poniendo-los-datos-en-forma.html#cb130-1"></a>agrupado &lt;-<span class="st"> </span><span class="kw">group_by</span>(atencion_ciudadano, AÑO, MES, BARRIO)</span>
<span id="cb130-2"><a href="poniendo-los-datos-en-forma.html#cb130-2"></a></span>
<span id="cb130-3"><a href="poniendo-los-datos-en-forma.html#cb130-3"></a>sumario &lt;-<span class="st"> </span><span class="kw">summarise</span>(agrupado, <span class="dt">promedio =</span> <span class="kw">mean</span>(total))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;AÑO&#39;, &#39;MES&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="poniendo-los-datos-en-forma.html#cb132-1"></a><span class="kw">head</span>(sumario)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
## # Groups:   AÑO, MES [1]
##   AÑO   MES   BARRIO    promedio
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;
## 1 2013  01    AGRONOMIA    14.6 
## 2 2013  01    ALMAGRO      29.5 
## 3 2013  01    BALVANERA    23.6 
## 4 2013  01    BARRACAS     19.4 
## 5 2013  01    BELGRANO     24.4 
## 6 2013  01    BOCA          9.97</code></pre>
<p>Con <code>summarise()</code> podemos usar cualquier función que tome una lista de valores y devuelva un sólo restado. Para empezar, algunas de las que más podrían ayudarnos son:</p>
<pre><code>* `mean()`: Obtiene el promedio de los valores
* `sum()`: Obtiene la suma
* `min()`: Obtiene el valor más bajo
* `max()`: Obtiene el valor más alto</code></pre>
</div>
<div id="bonus-el-operador-pipe" class="section level3" number="3.3.6">
<h3><span class="header-section-number">3.3.6</span> ¡BONUS! El operador “pipe”: <code>%&gt;%</code></h3>
<p>Antes de terminar, vamos a presentar una herramienta más: el operador <em>pipe</em> (pronúnciese “paip”, es el término en inglés que significa “tubo”).</p>
<p>El pipe es un operador: un símbolo que relaciona dos entidades. Dicho en forma más simple, el pipe de R, cuyo símbolo es <code>%&gt;%</code> está en familia con otros operadores más convencionales, como <code>+</code>, <code>-</code> o <code>/</code>. Y al igual que los otros operadores, entrega un resultado en base a los operandos que recibe. Ahora bien… ¿Para qué sirve? En resumidas cuentas, hace que el código necesario para realizar una serie de operaciones de transformación de datos sea mucho más simple de escribir y de interpretar.</p>
<p>Por ejemplo, si quisiéramos obtener el top 5 de los barrios que más reclamos y denuncias de los ciudadanos han registrado durante 2015, la forma de lograrlo en base a lo que ya sabemos sería así:</p>
<pre><code>1. Filtramos los datos para aislar los registros del 2014;
2. agrupamos por Barrio;
3. hacemos un sumario, creando una variable resumen que contiene la suma de los registros para cada barrio;
4. los ordenamos en forma descendiente,
5. mostramos sólo los primeros 5 (esto se puede hacer con la función `head()`, aclarando cuantas filas queremos ver)</code></pre>
<p>En código:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="poniendo-los-datos-en-forma.html#cb136-1"></a>solo2014 &lt;-<span class="st"> </span><span class="kw">filter</span>(atencion_ciudadano, AÑO <span class="op">==</span><span class="st"> </span><span class="dv">2014</span>)</span>
<span id="cb136-2"><a href="poniendo-los-datos-en-forma.html#cb136-2"></a></span>
<span id="cb136-3"><a href="poniendo-los-datos-en-forma.html#cb136-3"></a>solo2014_agrupado_barrio &lt;-<span class="st"> </span><span class="kw">group_by</span>(solo2014, BARRIO)</span>
<span id="cb136-4"><a href="poniendo-los-datos-en-forma.html#cb136-4"></a></span>
<span id="cb136-5"><a href="poniendo-los-datos-en-forma.html#cb136-5"></a>total_por_barrio_<span class="dv">2014</span> &lt;-<span class="st"> </span><span class="kw">summarise</span>(solo2014_agrupado_barrio, <span class="dt">total =</span> <span class="kw">sum</span>(total))</span>
<span id="cb136-6"><a href="poniendo-los-datos-en-forma.html#cb136-6"></a></span>
<span id="cb136-7"><a href="poniendo-los-datos-en-forma.html#cb136-7"></a>total_por_barrio_<span class="dv">2014</span>_ordenado &lt;-<span class="st"> </span><span class="kw">arrange</span>(total_por_barrio_<span class="dv">2014</span>, <span class="kw">desc</span>(total))</span>
<span id="cb136-8"><a href="poniendo-los-datos-en-forma.html#cb136-8"></a></span>
<span id="cb136-9"><a href="poniendo-los-datos-en-forma.html#cb136-9"></a><span class="kw">head</span>(total_por_barrio_<span class="dv">2014</span>_ordenado, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   BARRIO        total
##   &lt;chr&gt;         &lt;int&gt;
## 1 SAN NICOLAS  180956
## 2 PALERMO       22569
## 3 CABALLITO     19706
## 4 FLORES        15919
## 5 VILLA DEVOTO  15720</code></pre>
<p>¡Funciona! Pero… el problema es que hemos generado un puñado de variables (“solo2014”, “solo2014_agrupado_barrio”, etc) que, es probable, no volveremos a usar. Además de ser inútiles una vez obtenido el resultado buscado, estas variables intermedias requieren que las nombremos. Decidir el nombre de estas variables que no nos importan toma tiempo (sobre todo cuando producimos muchas), y nos distrae de lo importante, que es el análisis.</p>
<p>El pipe, <code>%&gt;%</code>, permite encadenar operaciones, conectando el resultado de una como el dato de entrada de la siguiente. La misma secuencia que realizamos antes puede resolverse con pipes, quedando así:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="poniendo-los-datos-en-forma.html#cb138-1"></a>atencion_ciudadano <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb138-2"><a href="poniendo-los-datos-en-forma.html#cb138-2"></a><span class="st">    </span><span class="kw">filter</span>(AÑO <span class="op">==</span><span class="st"> </span><span class="dv">2014</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb138-3"><a href="poniendo-los-datos-en-forma.html#cb138-3"></a><span class="st">    </span><span class="kw">group_by</span>(BARRIO) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb138-4"><a href="poniendo-los-datos-en-forma.html#cb138-4"></a><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">total =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb138-5"><a href="poniendo-los-datos-en-forma.html#cb138-5"></a><span class="st">    </span><span class="kw">arrange</span>(<span class="kw">desc</span>(total)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb138-6"><a href="poniendo-los-datos-en-forma.html#cb138-6"></a><span class="st">    </span><span class="kw">head</span>(<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   BARRIO        total
##   &lt;chr&gt;         &lt;int&gt;
## 1 SAN NICOLAS  180956
## 2 PALERMO       22569
## 3 CABALLITO     19706
## 4 FLORES        15919
## 5 VILLA DEVOTO  15720</code></pre>
<p>Una manera de pronunciar <code>%&gt;%</code> cuando leemos código es “y luego…”. Algo así como “tomamos el dataframe”atencion_ciudadano" y luego filtramos los registros del año 2014, y luego agrupamos por barrio, y luego calculamos el total de registros para cada grupo, y luego los ordenamos en forma descendente por total, y luego vemos los cinco primeros".</p>
<p>El uso de pipes permite concentrarse en las operaciones de transformación, y no en lo que está siendo transformado en cada paso. Esto hace al código mucho más sencillo de leer e interpretar. En el ejemplo con pipe, sólo tuvimos que nombrar un dataframe con el cual trabajar un única vez, al principio.</p>
<p>Detrás de escena, <code>x %&gt;% f(y)</code> se transforma en <code>f(x, y)</code>. Por eso,</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="poniendo-los-datos-en-forma.html#cb140-1"></a><span class="kw">filter</span>(atencion_ciudadano, AÑO <span class="op">==</span><span class="st"> </span><span class="dv">2014</span>)</span></code></pre></div>
<p>es equivalente a</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="poniendo-los-datos-en-forma.html#cb141-1"></a>atencion_ciudadano <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(AÑO <span class="op">==</span><span class="st"> </span><span class="dv">2014</span>)</span></code></pre></div>
<p>Trabajar con pipes es una de las ventajas que hacen de R un lenguaje muy expresivo y cómodo para manipular datos, y a partir de aquí lo usaremos de forma habitual.</p>
<p>Con esto cerramos la sección de transformación de datos. Las técnicas para examinar un dataframe, como <code>sumamry()</code> nos permiten entender de forma rápida con que clase de variables vamos a trabajar. Los cinco verbos de manipulación que aprendimos, usados en conjunto, brindan una enorme capacidad para adaptar el formato de los datos a nuestras necesidades. Y el operador pipe nos ayuda a escribir nuestro código de forma sucinta y fácil de interpretar.</p>
<p>A medida que vayamos progresando en nuestra familiaridad con las funciones -y agregando técnicas nuevas- vamos a ser capaces de procesar grandes cantidades de datos con soltura. Y obtener en pocos minutos lo que de otra forma, sin herramientas computacionales, tardaría días o sería inviable por lo tedioso.</p>
</div>
</div>
<div id="ejercicios-1" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Ejercicios</h2>
<p>I. Tomemos otro dataset, como el que descargamos durante los ejercicios del capítulo anterior, e intentemos:</p>
<ul>
<li>usar <code>select()</code> para seleccionar ciertas columnas y/o cambiar su orden</li>
<li>usar <code>filter()</code> para filtrar las filas, descartando las que no cumplan cierta condición o condiciones a elección</li>
<li>usar <code>arrange()</code> para ordenar el dataframe según alguna de sus variables</li>
<li>usar <code>mutate()</code> para crear una o más columnas nuevas</li>
<li>usar en combinación <code>group_by()</code> y <code>summarise()</code> para generar un resumen del dataset, que contenga al menos 3 variables (se pueden usar medias, máximos, conteos, etc)</li>
</ul>
<ol start="2" style="list-style-type: upper-roman">
<li>Si antes hicimos todos los pasos por separado, ahora intentemos hacer todo el procedimiento en una sola cadena de instrucciones usando el operador pipe: <code>%&gt;%</code></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="una-presentación-a-toda-marcha-de-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualización.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CD_AJ.pdf", "CD_AJ.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
